### ISSUE TITLE
crate_universe: Panic during repin

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/rules_rust#1265]
Sorry for the lack of information in this issue, there are some internal dependencies which prevent me from sharing the exact dependencies. I'll try to provide a better reproduction in the meantime. Though, if there are any ideas on what's happening it would be greatly appreciated!

rules_rust: 0.2.1

FWIW: Here's the offending line(s): https://github.com/bazelbuild/rules_rust/blob/c3f56c2d50c29c97c513f158bcb1dfef1bd52f1e/crate_universe/src/metadata/dependency.rs#L207-L208

```
❯ CARGO_NET_GIT_FETCH_WITH_CLI=true REPIN=1 bazel run //:buildifier
(21:49:15) INFO: Repository crate_index instantiated at:
  /Users/thomas/code/<redacted>/WORKSPACE:153:18: in <toplevel>
Repository rule crates_repository defined at:
  /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rules_rust/crate_universe/private/crates_repository.bzl:102:36: in <toplevel>
(21:49:15) ERROR: An error occurred during the fetch of repository 'crate_index':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rules_rust/crate_universe/private/crates_repository.bzl", line 74, column 22, in _crates_repository_impl
                execute_generator(
        File "/private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rules_rust/crate_universe/private/generate_utils.bzl", line 404, column 21, in execute_generator
                result = execute(
        File "/private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rules_rust/crate_universe/private/common_utils.bzl", line 40, column 13, in execute
                fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/cargo-bazel, "generate", "--lockfile", /Users/thomas/code/<redacted>/Cargo.Bazel.lock, "--lockfile-kind", "bazel", "--config", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/cargo-bazel.json, "--splicing-manifest", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/splicing_manifest.json, "--repository-dir", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index, "--cargo", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rust_darwin_aarch64/bin/cargo, "--rustc", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rust_darwin_aarch64/bin/rustc, "--repin", "--metadata", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/splicing-output/metadata.json] failed with exit code 101.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src/metadata/dependency.rs:208:5
stack backtrace:
   0:        0x104d091f8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h58c637f9e30d1b8a
   1:        0x104d2abf4 - core::fmt::write::hc16ca97d9f5e0acd
   2:        0x104d046d8 - std::io::Write::write_fmt::hd53dc7153ccce04d
   3:        0x104d0bcdc - std::panicking::default_hook::{{closure}}::ha41f2cf175ca93cf
   4:        0x104d0b884 - std::panicking::default_hook::h838498b157804a1a
   5:        0x104d0c2a0 - std::panicking::rust_panic_with_hook::h7722806c30430655
   6:        0x104d0c010 - std::panicking::begin_panic_handler::{{closure}}::h265229fa7cad6de7
   7:        0x104d096c4 - std::sys_common::backtrace::__rust_end_short_backtrace::hfa83d61d0ed14557
   8:        0x104d0bd78 - _rust_begin_unwind
   9:        0x104d49690 - core::panicking::panic_fmt::hd3f68d55261c2af0
  10:        0x104d292b8 - core::panicking::assert_failed_inner::h68efb5c219862afa
  11:        0x104d33804 - core::panicking::assert_failed::hc4f92a8dd5924056
  12:        0x10496bd08 - cargo_bazel::metadata::dependency::collect_deps_selectable::hf017bcd540b07cd7
  13:        0x10496ad94 - cargo_bazel::metadata::dependency::DependencySet::new_for_node::h49ba24fd2846b388
  14:        0x104a3cd90 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h31986db6161e0106
  15:        0x104a68e18 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h4a5da0a5ecc79365
  16:        0x10493316c - <alloc::collections::btree::map::BTreeMap<K,V> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter::hb30af9a67872b2de
  17:        0x104941080 - cargo_bazel::metadata::metadata_annotation::Annotations::new::h3d5db298bfd06963
  18:        0x104a29e4c - cargo_bazel::cli::generate::generate::h0fd06d1d5e5150fd
  19:        0x104894c24 - cargo_bazel::main::h774277219f15c573
  20:        0x104894ec0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h804dfabc8bdbc8ce
  21:        0x104894e44 - std::rt::lang_start::{{closure}}::habf3eec4f03811c0
  22:        0x104d089e4 - std::rt::lang_start_internal::h0c28bd035905a2f7
  23:        0x104894d94 - _main

(21:49:15) ERROR: /Users/thomas/code/<redacted>/WORKSPACE:153:18: fetching crates_repository rule //external:crate_index: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rules_rust/crate_universe/private/crates_repository.bzl", line 74, column 22, in _crates_repository_impl
                execute_generator(
        File "/private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rules_rust/crate_universe/private/generate_utils.bzl", line 404, column 21, in execute_generator
                result = execute(
        File "/private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rules_rust/crate_universe/private/common_utils.bzl", line 40, column 13, in execute
                fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/cargo-bazel, "generate", "--lockfile", /Users/thomas/code/<redacted>/Cargo.Bazel.lock, "--lockfile-kind", "bazel", "--config", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/cargo-bazel.json, "--splicing-manifest", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/splicing_manifest.json, "--repository-dir", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index, "--cargo", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rust_darwin_aarch64/bin/cargo, "--rustc", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rust_darwin_aarch64/bin/rustc, "--repin", "--metadata", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/splicing-output/metadata.json] failed with exit code 101.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src/metadata/dependency.rs:208:5
stack backtrace:
   0:        0x104d091f8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h58c637f9e30d1b8a
   1:        0x104d2abf4 - core::fmt::write::hc16ca97d9f5e0acd
   2:        0x104d046d8 - std::io::Write::write_fmt::hd53dc7153ccce04d
   3:        0x104d0bcdc - std::panicking::default_hook::{{closure}}::ha41f2cf175ca93cf
   4:        0x104d0b884 - std::panicking::default_hook::h838498b157804a1a
   5:        0x104d0c2a0 - std::panicking::rust_panic_with_hook::h7722806c30430655
   6:        0x104d0c010 - std::panicking::begin_panic_handler::{{closure}}::h265229fa7cad6de7
   7:        0x104d096c4 - std::sys_common::backtrace::__rust_end_short_backtrace::hfa83d61d0ed14557
   8:        0x104d0bd78 - _rust_begin_unwind
   9:        0x104d49690 - core::panicking::panic_fmt::hd3f68d55261c2af0
  10:        0x104d292b8 - core::panicking::assert_failed_inner::h68efb5c219862afa
  11:        0x104d33804 - core::panicking::assert_failed::hc4f92a8dd5924056
  12:        0x10496bd08 - cargo_bazel::metadata::dependency::collect_deps_selectable::hf017bcd540b07cd7
  13:        0x10496ad94 - cargo_bazel::metadata::dependency::DependencySet::new_for_node::h49ba24fd2846b388
  14:        0x104a3cd90 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h31986db6161e0106
  15:        0x104a68e18 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h4a5da0a5ecc79365
  16:        0x10493316c - <alloc::collections::btree::map::BTreeMap<K,V> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter::hb30af9a67872b2de
  17:        0x104941080 - cargo_bazel::metadata::metadata_annotation::Annotations::new::h3d5db298bfd06963
  18:        0x104a29e4c - cargo_bazel::cli::generate::generate::h0fd06d1d5e5150fd
  19:        0x104894c24 - cargo_bazel::main::h774277219f15c573
  20:        0x104894ec0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h804dfabc8bdbc8ce
  21:        0x104894e44 - std::rt::lang_start::{{closure}}::habf3eec4f03811c0
  22:        0x104d089e4 - std::rt::lang_start_internal::h0c28bd035905a2f7
  23:        0x104894d94 - _main

INFO: Reading rc options for 'run' from /Users/thomas/code/<redacted>/.bazelrc:
  Inherited 'build' options: --stamp --show_timestamps --workspace_status_command=scripts/workspace-status.sh --incompatible_enable_cc_toolchain_resolution --action_env=DOCKER_HOST --test_env=DOCKER_HOST --experimental_action_cache_store_output_metadata --experimental_remote_cache_async --experimental_remote_merkle_tree_cache --enable_platform_specific_config --@io_bazel_rules_go//go/config:linkmode=pie
ERROR: @io_bazel_rules_go//go/config:linkmode :: Error loading option @io_bazel_rules_go//go/config:linkmode: no such package '@crate_index//': Command [/private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/cargo-bazel, "generate", "--lockfile", /Users/thomas/code/<redacted>/Cargo.Bazel.lock, "--lockfile-kind", "bazel", "--config", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/cargo-bazel.json, "--splicing-manifest", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/splicing_manifest.json, "--repository-dir", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index, "--cargo", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rust_darwin_aarch64/bin/cargo, "--rustc", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/rust_darwin_aarch64/bin/rustc, "--repin", "--metadata", /private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/splicing-output/metadata.json] failed with exit code 101.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src/metadata/dependency.rs:208:5
stack backtrace:
   0:        0x104d091f8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h58c637f9e30d1b8a
   1:        0x104d2abf4 - core::fmt::write::hc16ca97d9f5e0acd
   2:        0x104d046d8 - std::io::Write::write_fmt::hd53dc7153ccce04d
   3:        0x104d0bcdc - std::panicking::default_hook::{{closure}}::ha41f2cf175ca93cf
   4:        0x104d0b884 - std::panicking::default_hook::h838498b157804a1a
   5:        0x104d0c2a0 - std::panicking::rust_panic_with_hook::h7722806c30430655
   6:        0x104d0c010 - std::panicking::begin_panic_handler::{{closure}}::h265229fa7cad6de7
   7:        0x104d096c4 - std::sys_common::backtrace::__rust_end_short_backtrace::hfa83d61d0ed14557
   8:        0x104d0bd78 - _rust_begin_unwind
   9:        0x104d49690 - core::panicking::panic_fmt::hd3f68d55261c2af0
  10:        0x104d292b8 - core::panicking::assert_failed_inner::h68efb5c219862afa
  11:        0x104d33804 - core::panicking::assert_failed::hc4f92a8dd5924056
  12:        0x10496bd08 - cargo_bazel::metadata::dependency::collect_deps_selectable::hf017bcd540b07cd7
  13:        0x10496ad94 - cargo_bazel::metadata::dependency::DependencySet::new_for_node::h49ba24fd2846b388
  14:        0x104a3cd90 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h31986db6161e0106
  15:        0x104a68e18 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h4a5da0a5ecc79365
  16:        0x10493316c - <alloc::collections::btree::map::BTreeMap<K,V> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter::hb30af9a67872b2de
  17:        0x104941080 - cargo_bazel::metadata::metadata_annotation::Annotations::new::h3d5db298bfd06963
  18:        0x104a29e4c - cargo_bazel::cli::generate::generate::h0fd06d1d5e5150fd
  19:        0x104894c24 - cargo_bazel::main::h774277219f15c573
  20:        0x104894ec0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h804dfabc8bdbc8ce
  21:        0x104894e44 - std::rt::lang_start::{{closure}}::habf3eec4f03811c0
  22:        0x104d089e4 - std::rt::lang_start_internal::h0c28bd035905a2f7
  23:        0x104894d94 - _main


```

**Comment by UebelAndre** [comment]
@uhthomas could you provide a WORKSPACE example of what dependencies you're using that lead to this issue?

**Comment by uhthomas** [comment]
Okay! I have a reproduction with https://github.com/uhthomas/rules_rust_1265.

```starlark
load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies", "rust_register_toolchains")

rules_rust_dependencies()

rust_register_toolchains()

load("@rules_rust//crate_universe:repositories.bzl", "crate_universe_dependencies")

crate_universe_dependencies()

load("@rules_rust//crate_universe:defs.bzl", "crates_repository", "crate")

crates_repository(
    name = "crate_index",
    lockfile = "//:Cargo.Bazel.lock",
    packages = {
        "xy-z": crate.spec(
            git = "https://github.com/uhthomas/rules_rust_1265",
            rev = "996b83e",
        ),
    },
)

load("@crate_index//:defs.bzl", "crate_repositories")

crate_repositories()
```

I added some debugging information to the generator which helps us to understand what's happening:

```diff
diff --git a/crate_universe/src/metadata/dependency.rs b/crate_universe/src/metadata/dependency.rs
index 105e4fe..00b04ee 100644
--- a/crate_universe/src/metadata/dependency.rs
+++ b/crate_universe/src/metadata/dependency.rs
@@ -204,6 +204,17 @@ fn get_library_target_name(package: &Package, potential_name: &str) -> String {
         .filter(|t| t.kind.iter().any(|k| k == "lib" || k == "proc-macro"))
         .collect();

+    if lib_targets.len() == 0 {
+        println!("potential name: {}", potential_name);
+        let target_names: Vec<String> = package
+            .targets
+            .iter()
+            .map(|t| t.name.to_string())
+            .collect();
+        println!("package targets: {:?}", target_names);
+        println!("package: {:#?}", package)
+    }
+
     // Only one target should be found
     assert_eq!(lib_targets.len(), 1);

```

Debug output:

```
potential name: xy_z
package targets: ["xy-z"]
package: Package {
    name: "xy-z",
    version: Version {
        major: 0,
        minor: 1,
        patch: 0,
    },
    authors: [],
    id: PackageId {
        repr: "xy-z 0.1.0 (git+https://github.com/uhthomas/rules_rust_1265?rev=996b83e#996b83e31c86f143de908466e9c7311877fdcba4)",
    },
    source: Some(
        Source {
            repr: "git+https://github.com/uhthomas/rules_rust_1265?rev=996b83e#996b83e31c86f143de908466e9c7311877fdcba4",
        },
    ),
    description: None,
    dependencies: [],
    license: None,
    license_file: None,
    targets: [
        Target {
            name: "xy-z",
            kind: [
                "rlib",
                "cdylib",
                "staticlib",
            ],
            crate_types: [
                "rlib",
                "cdylib",
                "staticlib",
            ],
            required_features: [],
            src_path: "/private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/.cargo_home/git/checkouts/rules_rust_1265-474d7b16cb06fef7/996b83e/abc/src/lib.rs",
            edition: "2015",
            doctest: true,
            test: true,
            doc: true,
        },
    ],
    features: {},
    manifest_path: "/private/var/tmp/_bazel_thomas/796dd52d4d981101108548a9446ddca6/external/crate_index/.cargo_home/git/checkouts/rules_rust_1265-474d7b16cb06fef7/996b83e/abc/Cargo.toml",
    categories: [],
    keywords: [],
    readme: None,
    repository: None,
    homepage: None,
    documentation: None,
    edition: "2015",
    metadata: Null,
    links: None,
    publish: None,
    default_run: None,
    rust_version: None,
}
```

It looks like something weird happens when packages use a hyphen, somewhere it gets transformed to an underscore and name matching becomes muddled. In our case, the crate is an FFI and so does not expose `lib` or `proc-macro` and causes the generator to panic.

**Comment by uhthomas** [comment]
We're currently patching rules_rust to circumvent this like so:

```diff
diff --git a/crate_universe/src/metadata/dependency.rs b/crate_universe/src/metadata/dependency.rs
index 105e4fe..96de8d5 100644
--- a/crate_universe/src/metadata/dependency.rs
+++ b/crate_universe/src/metadata/dependency.rs
@@ -201,9 +201,20 @@ fn get_library_target_name(package: &Package, potential_name: &str) -> String {
     let lib_targets: Vec<&cargo_metadata::Target> = package
         .targets
         .iter()
-        .filter(|t| t.kind.iter().any(|k| k == "lib" || k == "proc-macro"))
+        .filter(|t| t.kind.iter().any(|k| k == "lib" || k == "rlib" || k == "proc-macro"))
         .collect();
```

Would you be able to help me understand what the correct fix is? I'd be happy to help out.

**Comment by UebelAndre** [comment]
@uhthomas could I convince you to open a PR for this? 😅 🙏

**Comment by uhthomas** [comment]
>@uhthomas could I convince you to open a PR for this? 😅 🙏

Absolutely, though the snippet I've provided does not fix the original problem unfortunately. Do you have any guidance on what the correct behaviour is?
