### ISSUE TITLE
`workspace.dependencies` was not defined

### ISSUE THREAD

**Issue by pddg** [bazelbuild/rules_rust#1574]
Rust 1.64 is released. Inheriting dependencies from a workspace is now stable.
https://doc.rust-lang.org/stable/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace

However, it is not supported by `crate_universe`. Inheriting dependencies from workspace causes error during Repinning/Updating dependencies.

## Environment

- Rust 1.64.0
- bazel 5.3.0
- rules_rust 0.10.0

## How to reproduce

```bash
mkdir inherit_test
cd inherit_test
# Init bazel workspace
cat << 'EOF' > WORKSPACE
workspace(name = "inherit_from_workspace")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_rust",
    sha256 = "0cc7e6b39e492710b819e00d48f2210ae626b717a3ab96e048c43ab57e61d204",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_rust/releases/download/0.10.0/rules_rust-v0.10.0.tar.gz",
        "https://github.com/bazelbuild/rules_rust/releases/download/0.10.0/rules_rust-v0.10.0.tar.gz",
    ],
)
load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies", "rust_register_toolchains")
rules_rust_dependencies()
rust_register_toolchains(
    edition = "2021",
    version = "1.64.0",
)
load("@rules_rust//crate_universe:defs.bzl", "crates_repository")
crates_repository(
    name = "crate_index",
    cargo_lockfile = "//:Cargo.lock",
    lockfile = "//:Cargo.Bazel.lock",
    manifests = [
        "//:Cargo.toml",
        "//sub/hello:Cargo.toml"
    ],
    rust_version = "1.64.0",
)
load("@crate_index//:defs.bzl", "crate_repositories")
crate_repositories()
EOF
# Add dummy BUILD file
touch BUILD
# Add empty Cargo.Bazel.lock
touch Cargo.Bazel.lock
# Init cargo workspace
cargo init --name inherit-depends --edition 2021 .
rm -r src
cat << 'EOF' > Cargo.toml
[workspace]
members = ["sub/hello"]
[workspace.dependencies]
anyhow = "1.0.65"
EOF
# Add package which uses workspace inheritance.
mkdir -p sub/hello/src
cat << 'EOF' > sub/hello/Cargo.toml
[package]
name = "hello"
version = "0.1.0"
edition = "2021"
[dependencies]
anyhow = { workspace = true }
EOF
cat << 'EOF' > sub/hello/BUILD
load("@crate_index//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary")
rust_binary(
    name = "hello",
    srcs = glob(["src/**/*.rs"]),
    deps = all_crate_deps(
        normal = True,
    ),
)
EOF
cat << 'EOF' > sub/hello/src/main.rs
use anyhow::Result;

fn main() -> Result<()> {
    println!("hello world");
    Ok(())
}
EOF
```

It can run by cargo.

```bash
❯ cargo run -p hello
    Updating crates.io index
   Compiling anyhow v1.0.65
   Compiling hello v0.1.0 (/Users/pddg/Factory/inherit_test/sub/hello)
    Finished dev [unoptimized + debuginfo] target(s) in 2.69s
     Running `target/debug/hello`
hello world
```

An error occurred during repinning/updating dependencies.

```bash
CARGO_BAZEL_REPIN=true bazel sync --only=crate_index
```

<details>
<summary>Error message</summary>

```
Starting local Bazel server and connecting to it...
INFO: Repository crate_index instantiated at:
  /Users/pddg/Factory/inherit_test/WORKSPACE:18:18: in <toplevel>
Repository rule crates_repository defined at:
  /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/crates_repository.bzl:106:36: in <toplevel>
INFO: Repository 'crate_index' used the following cache hits instead of downloading the corresponding file.
 * Hash '4104ea8edd3fccbcfc43265e4fa02dfc25b12b32250ff46456b829ab9cb78908' for https://github.com/bazelbuild/rules_rust/releases/download/0.10.0/cargo-bazel-aarch64-apple-darwin
If the definition of 'crate_index' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'crate_index':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/crates_repository.bzl", line 59, column 50, in _crates_repository_impl
		metadata_path = splice_workspace_manifest(
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/splicing_utils.bzl", line 168, column 12, in splice_workspace_manifest
		execute(
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/common_utils.bzl", line 44, column 13, in execute
		fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing_manifest.json, "--cargo", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/rustc, "--cargo-lockfile", /Users/pddg/Factory/inherit_test/Cargo.lock] failed with exit code 1.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------

error: failed to load manifest for workspace member `/var/folders/r3/ys126msj43dfk6gp9tmq9nm40000gn/T/.tmplLfqhd/sub/hello`

Caused by:
  failed to parse manifest at `/var/folders/r3/ys126msj43dfk6gp9tmq9nm40000gn/T/.tmplLfqhd/sub/hello/Cargo.toml`

Caused by:
  error reading `dependencies.anyhow` from workspace root manifest's `workspace.dependencies.anyhow`

Caused by:
  `workspace.dependencies` was not defined

Error: Failed to update lockfile: exit status: 101

ERROR: /Users/pddg/Factory/inherit_test/WORKSPACE:18:18: fetching crates_repository rule //external:crate_index: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/crates_repository.bzl", line 59, column 50, in _crates_repository_impl
		metadata_path = splice_workspace_manifest(
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/splicing_utils.bzl", line 168, column 12, in splice_workspace_manifest
		execute(
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/common_utils.bzl", line 44, column 13, in execute
		fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing_manifest.json, "--cargo", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/rustc, "--cargo-lockfile", /Users/pddg/Factory/inherit_test/Cargo.lock] failed with exit code 1.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------

error: failed to load manifest for workspace member `/var/folders/r3/ys126msj43dfk6gp9tmq9nm40000gn/T/.tmplLfqhd/sub/hello`

Caused by:
  failed to parse manifest at `/var/folders/r3/ys126msj43dfk6gp9tmq9nm40000gn/T/.tmplLfqhd/sub/hello/Cargo.toml`

Caused by:
  error reading `dependencies.anyhow` from workspace root manifest's `workspace.dependencies.anyhow`

Caused by:
  `workspace.dependencies` was not defined

Error: Failed to update lockfile: exit status: 101

ERROR: no such package '@crate_index//': Command [/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing_manifest.json, "--cargo", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/rustc, "--cargo-lockfile", /Users/pddg/Factory/inherit_test/Cargo.lock] failed with exit code 1.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------

error: failed to load manifest for workspace member `/var/folders/r3/ys126msj43dfk6gp9tmq9nm40000gn/T/.tmplLfqhd/sub/hello`

Caused by:
  failed to parse manifest at `/var/folders/r3/ys126msj43dfk6gp9tmq9nm40000gn/T/.tmplLfqhd/sub/hello/Cargo.toml`

Caused by:
  error reading `dependencies.anyhow` from workspace root manifest's `workspace.dependencies.anyhow`

Caused by:
  `workspace.dependencies` was not defined

Error: Failed to update lockfile: exit status: 101

Loading: loading...
```

</details>

**Comment by pddg** [comment]
@UebelAndre 
I confirmed that it works perfectly with some dependencies inherited from workspace!
Thank you!

However, support for workspace inheritance does not yet appear to be complete. For example, in Cargo, it is possible to specify `edition` on Cargo.toml at workspace root.

Cargo.toml at workspace root
```toml
[workspace.package]
edition = "2021"
```

Cargo.toml at each member
```toml
[package]
edition = { workdpace = true }
```

Run `bazel sync`, then it causes an error like this:

```
unknown variant `workspace`, expected one of `2015`, `2018`, `2021` for key `package.edition` at line 5 column 1
```

<details>
<summary>Full error message</summary>

```
❯ CARGO_BAZEL_REPIN=true bazel sync --only=crate_index
INFO: Repository crate_index instantiated at:
  /Users/pddg/Factory/inherit_test/WORKSPACE:18:18: in <toplevel>
Repository rule crates_repository defined at:
  /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/crates_repository.bzl:106:36: in <toplevel>
INFO: Repository 'crate_index' used the following cache hits instead of downloading the corresponding file.
 * Hash 'cb6db36f817ce19d5b5e95fcf18a31a3b8bba945b9e2d1051aa5aac6195e35cb' for https://github.com/bazelbuild/rules_rust/releases/download/0.11.0/cargo-bazel-aarch64-apple-darwin
If the definition of 'crate_index' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'crate_index':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/crates_repository.bzl", line 59, column 50, in _crates_repository_impl
		metadata_path = splice_workspace_manifest(
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/splicing_utils.bzl", line 177, column 12, in splice_workspace_manifest
		execute(
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/common_utils.bzl", line 44, column 13, in execute
		fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing_manifest.json, "--cargo", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/rustc, "--cargo-lockfile", /Users/pddg/Factory/inherit_test/Cargo.lock] failed with exit code 1.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
Error: Failed to read manifest at /Users/pddg/Factory/inherit_test/sub/hello/Cargo.toml

Caused by:
    0: Failed to deserialize manifest
    1: unknown variant `workspace`, expected one of `2015`, `2018`, `2021` for key `package.edition` at line 5 column 1
    2: unknown variant `workspace`, expected one of `2015`, `2018`, `2021` for key `package.edition` at line 5 column 1

ERROR: /Users/pddg/Factory/inherit_test/WORKSPACE:18:18: fetching crates_repository rule //external:crate_index: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/crates_repository.bzl", line 59, column 50, in _crates_repository_impl
		metadata_path = splice_workspace_manifest(
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/splicing_utils.bzl", line 177, column 12, in splice_workspace_manifest
		execute(
	File "/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rules_rust/crate_universe/private/common_utils.bzl", line 44, column 13, in execute
		fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing_manifest.json, "--cargo", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/rustc, "--cargo-lockfile", /Users/pddg/Factory/inherit_test/Cargo.lock] failed with exit code 1.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
Error: Failed to read manifest at /Users/pddg/Factory/inherit_test/sub/hello/Cargo.toml

Caused by:
    0: Failed to deserialize manifest
    1: unknown variant `workspace`, expected one of `2015`, `2018`, `2021` for key `package.edition` at line 5 column 1
    2: unknown variant `workspace`, expected one of `2015`, `2018`, `2021` for key `package.edition` at line 5 column 1

ERROR: no such package '@crate_index//': Command [/private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/crate_index/splicing_manifest.json, "--cargo", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_pddg/e23dee73eaecf6e00719f298339410dd/external/rust_darwin_aarch64__aarch64-apple-darwin_tools/bin/rustc, "--cargo-lockfile", /Users/pddg/Factory/inherit_test/Cargo.lock] failed with exit code 1.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
Error: Failed to read manifest at /Users/pddg/Factory/inherit_test/sub/hello/Cargo.toml

Caused by:
    0: Failed to deserialize manifest
    1: unknown variant `workspace`, expected one of `2015`, `2018`, `2021` for key `package.edition` at line 5 column 1
    2: unknown variant `workspace`, expected one of `2015`, `2018`, `2021` for key `package.edition` at line 5 column 1

Loading: loading...
```

</details>

However, this is not (directly) the same issue as the one I originally reported.
Should I make another issue?

**Comment by UebelAndre** [comment]
That does sound like a separate topic. Could you file a new issue?
