### ISSUE TITLE
"Cargo-free" setup - workspace splicing times out

### ISSUE THREAD

**Issue by mattbonnell** [bazelbuild/rules_rust#1608]
Here's the relevant part of my WORKSPACE
```
#-- Rust begin --#
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# To find additional information on this release or newer ones visit:
# https://github.com/bazelbuild/rules_rust/releases
http_archive(
    name = "rules_rust",
    sha256 = "696b01deea96a5e549f1b5ae18589e1bbd5a1d71a36a243b5cf76a9433487cf2",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_rust/releases/download/0.11.0/rules_rust-v0.11.0.tar.gz",
        "https://github.com/bazelbuild/rules_rust/releases/download/0.11.0/rules_rust-v0.11.0.tar.gz",
    ],
)

load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies", "rust_register_toolchains")

rules_rust_dependencies()

rust_register_toolchains(
    edition = "2021",
    version = "1.64.0",
)

load("@rules_rust//crate_universe:repositories.bzl", "crate_universe_dependencies")

crate_universe_dependencies()

# From http://bazelbuild.github.io/rules_rust/crate_universe.html#direct-packages
load("@rules_rust//crate_universe:defs.bzl", "crate", "crates_repository", "render_config")

crates_repository(
    name = "crate_index",
    cargo_lockfile = "//:Cargo.Bazel.lock",
    packages = {
        "rand": crate.spec(
            version = "0.8.4",
        ),
        "async-trait": crate.spec(
            version = "0.1.51",
        ),
        "mockall": crate.spec(
            version = "0.10.2",
        ),
        "tokio": crate.spec(
            version = "1.12.0",
        ),
    },
    # Setting the default package name to `""` forces the use of the macros defined in this repository
    # to always use the root package when looking for dependencies or aliases. This should be considered
    # optional as the repository also exposes alises for easy access to all dependencies.
    render_config = render_config(
        default_package_name = "",
    ),
)

load("@crate_index//:defs.bzl", "crate_repositories")

crate_repositories()

# From http://bazelbuild.github.io/rules_rust/rust_analyzer.html
load("@rules_rust//tools/rust_analyzer:deps.bzl", "rust_analyzer_dependencies")

rust_analyzer_dependencies()

#-- Rust end --#
```

The `Cargo.Bazel.lock` file is empty.

I run the following to update the dependencies
```
CARGO_BAZEL_REPIN=1 bazel sync --only=crate_index
```

and it hangs on `Splicing cargo workspace`:
```
Loading: loading...
    Fetching @crate_index; Splicing Cargo workspace. 567s
```

Finally, it times out with this error
```
INFO: Repository crate_index instantiated at:
  /Users/mabonnell/data-platforms-analytics/dataworks/WORKSPACE:189:18: in <toplevel>
Repository rule crates_repository defined at:
  /private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/rules_rust/crate_universe/private/crates_repository.bzl:106:36: in <toplevel>
INFO: Repository 'crate_index' used the following cache hits instead of downloading the corresponding file.
 * Hash '2a2a0eedf759d6ff8ed851b822af1ea1e79e7a8e8781864ece120f9bbc8dc3c1' for https://github.com/bazelbuild/rules_rust/releases/download/0.11.0/cargo-bazel-x86_64-apple-darwin
If the definition of 'crate_index' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'crate_index':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/rules_rust/crate_universe/private/crates_repository.bzl", line 59, column 50, in _crates_repository_impl
                metadata_path = splice_workspace_manifest(
        File "/private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/rules_rust/crate_universe/private/splicing_utils.bzl", line 177, column 12, in splice_workspace_manifest
                execute(
        File "/private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/rules_rust/crate_universe/private/common_utils.bzl", line 44, column 13, in execute
                fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa
042f28312/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/crate_index/splicing_manifest.json, "--cargo", /private/var/t
mp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/rust_darwin_x86_64__x86_64-apple-darwin_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/ru
st_darwin_x86_64__x86_64-apple-darwin_tools/bin/rustc, "--cargo-lockfile", /Users/mabonnell/data-platforms-analytics/dataworks/Cargo.Bazel.lock] failed with exit code 256.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
Timed out
ERROR: /Users/mabonnell/data-platforms-analytics/dataworks/WORKSPACE:189:18: fetching crates_repository rule //external:crate_index: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/rules_rust/crate_universe/private/crates_repository.bzl", line 59, column 50, in _crates_repository_impl
                metadata_path = splice_workspace_manifest(
        File "/private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/rules_rust/crate_universe/private/splicing_utils.bzl", line 177, column 12, in splice_workspace_manifest
                execute(
        File "/private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/rules_rust/crate_universe/private/common_utils.bzl", line 44, column 13, in execute
                fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa
042f28312/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/crate_index/splicing_manifest.json, "--cargo", /private/var/t
mp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/rust_darwin_x86_64__x86_64-apple-darwin_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/ru
st_darwin_x86_64__x86_64-apple-darwin_tools/bin/rustc, "--cargo-lockfile", /Users/mabonnell/data-platforms-analytics/dataworks/Cargo.Bazel.lock] failed with exit code 256.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
Timed out
ERROR: no such package '@crate_index//': Command [/private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/crate_index/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_mabonne
ll/03580042f6da2d1e10179fa042f28312/external/crate_index/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/crate_index/splicing_manifest.json,
 "--cargo", /private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10179fa042f28312/external/rust_darwin_x86_64__x86_64-apple-darwin_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_mabonnell/03580042f6da2d1e10
179fa042f28312/external/rust_darwin_x86_64__x86_64-apple-darwin_tools/bin/rustc, "--cargo-lockfile", /Users/mabonnell/data-platforms-analytics/dataworks/Cargo.Bazel.lock] failed with exit code 256.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------
Timed out
Loading: loading...
```

**Comment by mattbonnell** [comment]
If I remove the `packages` map, it returns successfully

**Comment by UebelAndre** [comment]
In general the thing that takes the longest when splicing is running a `cargo update`. Are you sure this isn't constrained on your network and is genuinely taking a long time? I've seen this be the case whenever someone runs this for the first time on their host. Perhaps try setting [crates_repository.isolated](https://bazelbuild.github.io/rules_rust/crate_universe.html#crates_repository-isolated) to `False`? This way the results of the previous invocation are cached to `${HOME}/.cargo`

**Comment by mattbonnell** [comment]
This worked, thank you
