### ISSUE TITLE
The following chain of repository dependencies lead to the missing definition

### ISSUE THREAD

**Issue by QuentinPerez** [bazelbuild/rules_rust#1709]
Since the `0.15.0`, I can not build anymore due to the following error, has something changed ? 

```
rust_register_toolchains(
    edition = "2021",
    extra_target_triples = [
        "aarch64-apple-ios-sim",
        "aarch64-apple-ios",
        "aarch64-linux-android",
        "x86_64-unknown-linux-gnu",
    ],
    # rustup default nightly-2022-12-12
    include_rustc_srcs = True,
    iso_date = "2022-12-12",
    rustfmt_version = "nightly",
    version = "nightly",
)

...

> CARGO_BAZEL_REPIN=true bazel query //...

The following chain of repository dependencies lead to the missing definition.
 - @crate_index
 - @rust_darwin_aarch64__aarch64-apple-darwin__stable_tools
This could either mean you have to add the '@rust_darwin_aarch64__aarch64-apple-darwin__stable_tools' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
```

**Comment by UebelAndre** [comment]
This can occur if you have custom toolchains defined. Is that the case?

**Comment by UebelAndre** [comment]
Oh, I'm sorry, I see the issue. Try replacing `iso_date` and `version` with
```starlark
versions = [
    "nightly/2022-12-12",
    "1.66.0",
]
```

Either that or you can update your `crates_repository` definitions to force the `{channel}` parameter on [rust_toolchain_rustc_template](https://bazelbuild.github.io/rules_rust/crate_universe.html#crates_repository-rust_toolchain_rustc_template) and [rust_toolchain_cargo_template](https://bazelbuild.github.io/rules_rust/crate_universe.html#crates_repository-rust_toolchain_cargo_template) to explicitly be set to `nightly`. Sorry about the miscommunication there.

**Comment by QuentinPerez** [comment]
Thank you for the answers, no worries.

> This can occur if you have custom toolchains defined. Is that the case?

any

I got the same issue with `versions = ["nightly/2022-12-12"]`, it goes further with `versions = ["nightly/2022-12-12",  "1.66.0"]` and I had this one.
```
ERROR: An error occurred during the fetch of repository 'rust_darwin_aarch64__aarch64-apple-darwin__stable_tools':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_quentinperez/e75744411739bef331d606bc869abdf6/external/rules_rust/rust/repositories.bzl", line 243, column 45, in _rust_toolchain_tools_repository_impl
                build_components.append(load_rustfmt(ctx))
        File "/private/var/tmp/_bazel_quentinperez/e75744411739bef331d606bc869abdf6/external/rules_rust/rust/private/repository_utils.bzl", line 360, column 24, in load_rustfmt
                load_arbitrary_tool(
        File "/private/var/tmp/_bazel_quentinperez/e75744411739bef331d606bc869abdf6/external/rules_rust/rust/private/repository_utils.bzl", line 685, column 24, in load_arbitrary_tool
                check_version_valid(version, iso_date, param_prefix = tool_name + "_")
        File "/private/var/tmp/_bazel_quentinperez/e75744411739bef331d606bc869abdf6/external/rules_rust/rust/private/repository_utils.bzl", line 599, column 13, in check_version_valid
                fail("{param_prefix}iso_date must be specified if version is 'beta' or 'nightly'".format(param_prefix = param_prefix))
Error in fail: rustfmt_iso_date must be specified if version is 'beta' or 'nightly'
```
I tried to set the `rustfmt_iso_date` but it seems that it's not a parameters of `rust_register_toolchains`

**Comment by QuentinPerez** [comment]
it works with 
```
crates_repository(
...
    rust_toolchain_cargo_template = "@rust_{system}_{arch}__{triple}__nightly_tools//:bin/{tool}",
    rust_toolchain_rustc_template = "@rust_{system}_{arch}__{triple}__nightly_tools//:bin/{tool}",
)
```

**Comment by UebelAndre** [comment]
Hmm, could you try applying the following diff and see what happens?
```diff
diff --git a/rust/private/repository_utils.bzl b/rust/private/repository_utils.bzl
index 50968b59..4ca8d8bc 100644
--- a/rust/private/repository_utils.bzl
+++ b/rust/private/repository_utils.bzl
@@ -596,7 +596,10 @@ def check_version_valid(version, iso_date, param_prefix = ""):
         fail("{param_prefix}iso_date must be paired with a {param_prefix}version".format(param_prefix = param_prefix))

     if version in ("beta", "nightly") and not iso_date:
-        fail("{param_prefix}iso_date must be specified if version is 'beta' or 'nightly'".format(param_prefix = param_prefix))
+        fail("{param_prefix}iso_date must be specified if version is 'beta' or 'nightly'. Got: {value}".format(
+            param_prefix = param_prefix,
+            value = version,
+        ))

 def produce_tool_suburl(tool_name, target_triple, version, iso_date = None):
     """Produces a fully qualified Rust tool name for URL
diff --git a/rust/repositories.bzl b/rust/repositories.bzl
index 08c8370e..d0887dc9 100644
--- a/rust/repositories.bzl
+++ b/rust/repositories.bzl
@@ -700,7 +700,7 @@ def rust_repository_set(
                 edition = edition,
                 exec_triple = exec_triple,
                 include_rustc_srcs = include_rustc_srcs,
-                iso_date = info.iso_date,
+                iso_date = info.iso_date or (iso_date if rustfmt_version in ("nightly", "beta") else None),
                 rustfmt_version = rustfmt_version,
                 sha256s = sha256s,
                 target_triple = target_triple,
```

**Comment by UebelAndre** [comment]
Also, you may want to try adding `common --@rules_rust//rust/toolchain/channel=nightly` to your `.bazelrc` file if the above doesn't work. This would default the toolchains registerd to nightly toolchains should you have two registered. But my hope is that we can get your repo back to it's original working state without additional toolchains.

**Comment by UebelAndre** [comment]
> but when I try to cross compile for `aarch64-apple-ios`, the toolchain is missing `No matching toolchains found for types @rules_rust//rust:toolchain_type.`

Can you show me a build with `--toolchain_debug` enabled? What previously matched and what is now not matching your cross target?

**Comment by QuentinPerez** [comment]
> > but when I try to cross compile for `aarch64-apple-ios`, the toolchain is missing `No matching toolchains found for types @rules_rust//rust:toolchain_type.`
> 
> Can you show me a build with `--toolchain_debug` enabled? What previously matched and what is now not matching your cross target?

sure, here is the result.

```
INFO: Build option --toolchain_resolution_debug has changed, discarding analysis cache.
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_darwin_aarch64__aarch64-apple-darwin__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_darwin_aarch64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_darwin_aarch64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_darwin_aarch64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_darwin_aarch64__aarch64-apple-darwin__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_darwin_aarch64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_darwin_aarch64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_darwin_aarch64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_darwin_aarch64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_windows_aarch64__aarch64-pc-windows-msvc__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_windows_aarch64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_windows_aarch64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_windows_aarch64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_windows_aarch64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_linux_aarch64__aarch64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_linux_aarch64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_linux_aarch64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_linux_aarch64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_linux_aarch64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_darwin_x86_64__x86_64-apple-darwin__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_darwin_x86_64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_darwin_x86_64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_darwin_x86_64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_darwin_x86_64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_windows_x86_64__x86_64-pc-windows-msvc__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_windows_x86_64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_windows_x86_64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_windows_x86_64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_windows_x86_64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_freebsd_x86_64__x86_64-unknown-freebsd__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_freebsd_x86_64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_freebsd_x86_64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_freebsd_x86_64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_freebsd_x86_64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_linux_x86_64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_linux_x86_64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_linux_x86_64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_linux_x86_64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: Rejected toolchain @rust_linux_x86_64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:   Type @rules_rust//rust:toolchain_type: target platform @local_config_platform//:host: No toolchains found.
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_darwin_aarch64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_windows_aarch64__aarch64-pc-windows-msvc__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_windows_aarch64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_windows_aarch64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_windows_aarch64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_windows_aarch64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_linux_aarch64__aarch64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_linux_aarch64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_linux_aarch64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_linux_aarch64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_linux_aarch64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_darwin_x86_64__x86_64-apple-darwin__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_darwin_x86_64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_darwin_x86_64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_darwin_x86_64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_darwin_x86_64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_windows_x86_64__x86_64-pc-windows-msvc__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_windows_x86_64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_windows_x86_64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_windows_x86_64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_windows_x86_64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_freebsd_x86_64__x86_64-unknown-freebsd__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_freebsd_x86_64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_freebsd_x86_64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_freebsd_x86_64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_freebsd_x86_64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_linux_x86_64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_linux_x86_64__aarch64-apple-ios-sim__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_linux_x86_64__aarch64-apple-ios__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_linux_x86_64__aarch64-linux-android__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:     Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: Rejected toolchain @rust_linux_x86_64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain; mismatching config settings: nightly
INFO: ToolchainResolution:   Type @rules_rust//rust:toolchain_type: target platform //:ios_sim_arm64: No toolchains found.
```

**Comment by QuentinPerez** [comment]
there is no cross compile issue with  `--@rules_rust//rust/toolchain/channel=nightly`

**Comment by QuentinPerez** [comment]
@UebelAndre 👋  happy new year !
 
Just tried the `0.16` and it seems that I still need to specify 

```
build --@rules_rust//rust/toolchain/channel=nightly
```

and 
```
    rust_toolchain_cargo_template = "@rust_{system}_{arch}__{triple}__nightly_tools//:bin/{tool}",
    rust_toolchain_rustc_template = "@rust_{system}_{arch}__{triple}__nightly_tools//:bin/{tool}",
```

is it normal ? also not sure if it's related but I can't build anymore without `CARGO_BAZEL_REPIN=true`.
any bazel command ends with an `out of date lockfile`

**Comment by UebelAndre** [comment]
> @UebelAndre 👋 happy new year !

Thank! You too 😄 



> Just tried the `0.16` and it seems that I still need to specify
> 
> ```
> build --@rules_rust//rust/toolchain/channel=nightly
> ```
> 
> and
> 
> ```
>     rust_toolchain_cargo_template = "@rust_{system}_{arch}__{triple}__nightly_tools//:bin/{tool}",
>     rust_toolchain_rustc_template = "@rust_{system}_{arch}__{triple}__nightly_tools//:bin/{tool}",
> ```

This is expected. It is unfortunately an oversight in recent changes to introduce transitions for toolchain channels. In `0.16.0`, fixes were merged but it still seems there's a gap in the user experience here for users of `crate_universe`. For the out of date lockfiles, I believe changing those templates will invalidate lockfiles and force you to repin. In `0.16.0`, the behavior of repinning changed to default to only repinning workspace dependencies. So if you repin I would expect only the hash at the top of the file would change.

@illicitonion I'm wondering if you have any thoughts on how to improve this. The new ability to transition is very valuable in code I work on and so would like to keep the functionality but it does seem users who want to use nightly toolchains must now set an additional flag.

**Comment by QuentinPerez** [comment]
thank you for the answer, about the lockfile even after launching a command with repin=true the next one considers the lockfile out of date, means that I have to specify repin=true all the time.

**Comment by UebelAndre** [comment]
That’s a major bug then. Can you share your `rules_rust` and` `crates_repository` definitions?

**Comment by UebelAndre** [comment]
Sorry, I didn't realize it was earlier in the thread. Instead of modifying the templates, can you try setting `rust_version` on your `crates_repository` definition?

**Comment by QuentinPerez** [comment]
> Sorry, I didn't realize it was earlier in the thread. Instead of modifying the templates, can you try setting `rust_version` on your `crates_repository` definition?

Can't use `version` anymore, it should be deprecated but when you use it, there is the following error.

```
rust_register_toolchains(
    edition = "2021",
    version = "nightly",
)
```

`Error in fail: `version` and `versions` attributes are mutually exclusive. Update rust_darwin_aarch64 to use one`

**Comment by UebelAndre** [comment]
Update `rust_register_toolchains` to 
```starlark
rust_register_toolchains(
    edition = "2021",
    versions = "nightly/2022-12-15",
)
```

Then update your `crates_repository` call to
```starlark
crates_repository(
    # ...
    rust_version = "nightly/2022-12-15"
    # ...
)
```
That's specifically what I'm referring to.

**Comment by QuentinPerez** [comment]
thx, look goods, I don't have to specify `rust_toolchain_*_template` but I still have to keep the `build --@rules_rust//rust/toolchain/channel=nightly` for the crosscompilation :)

**Comment by UebelAndre** [comment]
Yeah, that's expected. I can update the docs to inform users about this flag.
