### ISSUE TITLE
Build fail when depending on a library in a different repo that mixes generated and non-generated sources

### ISSUE THREAD

**Issue by dmitrii-ubskii** [bazelbuild/rules_rust#1780]
rules_rust v0.16.1, Bazel v5.1.1 & v6.0.0.

Scenario: a common library has bindings for a number of different languages, one of which is Rust. `rust/BUILD` in the library defines a rule to generate the bindings as well as the `rust_library` rule that includes some helpful wrapper functions. 

```bazel
# @lib//rust:BUILD
load("@rules_rust//rust:defs.bzl", "rust_library")

genrule(
    name = "gen",
    cmd = "echo 'pub fn hello() { println!(\"Hello, world!\"); }' > $(@D)/gen.rs",
    outs = ["src/gen.rs"],
)

rust_library(
    name = "lib-with-gen",
    srcs = ["src/lib.rs", ":gen"],
    visibility = ["//visibility:public"],
)
```

Another repository wants to use the bindings as a library dependency. We import the `git_repository` as `lib` and attempt to use `@lib//rust:lib-with-gen` as a dependency. 

```bazel
# @bin//:BUILD
load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "bin",
    srcs = ["src/main.rs"],
    deps = ["@lib//rust:lib-with-gen"],
)
```

However, the build fails:

```
...$ bazel build //:bin
ERROR: /private/var/tmp/.../external/lib/rust/BUILD:9:13: in rust_library rule @lib//rust:lib-with-gen: 
Traceback (most recent call last):
        File "/private/var/tmp/.../external/rules_rust/rust/private/rust.bzl", line 197, column 32, in _rust_library_impl
                return _rust_library_common(ctx, "rlib")
        File "/private/var/tmp/.../external/rules_rust/rust/private/rust.bzl", line 253, column 42, in _rust_library_common
                srcs, crate_root = _transform_sources(ctx, ctx.files.srcs, getattr(ctx.file, "crate_root", None))
        File "/private/var/tmp/.../external/rules_rust/rust/private/rust.bzl", line 172, column 68, in _transform_sources
                src_symlink = ctx.actions.declare_file(paths.relativize(src.short_path, package_root))
        File "/private/var/tmp/.../external/bazel_skylib/lib/paths.bzl", line 186, column 17, in _relativize
                fail("Path '%s' is not beneath '%s'" % (path, start))
Error in fail: Path '../lib/rust/src/lib.rs' is not beneath 'rust'
ERROR: /private/var/tmp/.../external/lib/rust/BUILD:9:13: Analysis of target '@lib//rust:lib-with-gen' failed
ERROR: Analysis of target '//:bin' failed; build aborted: 
INFO: Elapsed time: 1.257s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 3 targets configured)
```

The build does not fail if both targets are in the same repository, nor does it fail if the library is at the root of its repo (i.e. `@lib//:lib-with-gen`). The build also does not fail if all sources are generated, or if none of them are.

MRE:
lib: https://github.com/dmitrii-ubskii/rules-rust-mre-external
bin: https://github.com/dmitrii-ubskii/rules-rust-mre-main

**Comment by dmitrii-ubskii** [comment]
A similar issue was mentioned in https://github.com/bazelbuild/rules_rust/issues/1530#issuecomment-1364316303

**Comment by dmitrii-ubskii** [comment]
Added `print((src.root.path, src.path, src.short_path, package_root))` before rules_rust/rust/private/rust.bzl:172. Result: `("", "external/lib/rust/src/lib.rs", "../lib/rust/src/lib.rs", "rust")`
