### ISSUE TITLE
Fix CI infrastructure issue on "Clang and LDD" jobs

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#1784]
CI started failing with what appears to be an infrastructure failure in Bazel CI. This issue tracks the resolution

https://buildkite.com/bazel/rules-rust-rustlang/builds/7901#0185c305-084d-419f-a7e5-b97a76171d1a
```
set -e
sudo apt -y update && sudo apt -y install lld
Get:1 https://download.docker.com/linux/ubuntu focal InRelease [57.7 kB]
Get:2 http://packages.cloud.google.com/apt cloud-sdk InRelease [6361 B]
Get:3 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages [25.7 kB]
Err:2 http://packages.cloud.google.com/apt cloud-sdk InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
Get:4 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]      
Get:6 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [27.7 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [980 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
Get:11 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [1864 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:14 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2425 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [31.2 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [1989 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2899 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1281 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
Get:21 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
Reading package lists... Done                           
W: GPG error: http://packages.cloud.google.com/apt cloud-sdk InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
E: The repository 'http://packages.cloud.google.com/apt cloud-sdk InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Traceback (most recent call last):
  File "bazelci.py", line 3594, in <module>
    sys.exit(main())
  File "bazelci.py", line 3561, in main
    execute_commands(
  File "bazelci.py", line 1295, in execute_commands
    execute_shell_commands(task_config.get("shell_commands", None))
  File "bazelci.py", line 1723, in execute_shell_commands
    execute_command([shell_command], shell=True)
  File "bazelci.py", line 2255, in execute_command
    return subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['set -e\nsudo apt -y update && sudo apt -y install lld']' returned non-zero exit status 100.
🚨 Error: The command exited with status 1
user command error: The plugin docker command hook exited with status 1
```

**Comment by UebelAndre** [comment]
cc @scentini @krasimirgg @hlopko

Could a Googler take a look?

**Comment by UebelAndre** [comment]
https://github.com/bazelbuild/rules_rust/pull/1785 temporarily disables the failing jobs.

**Comment by scentini** [comment]
I'm also seeing this on other projects: https://buildkite.com/bazel/kythe/builds/6263 https://buildkite.com/bazel/rules-haskell-haskell/builds/1381#0185bde6-fd3d-4ce3-9230-e4772fb60bba https://buildkite.com/bazel/upb/builds/1388#0185c30d-74df-4d46-9e49-0893fb354d2d

@meteorcloudy could you PTAL or triage?
