### ISSUE TITLE
rules_rust is failling with "Error: 'apple_linking_output' value has no field or method 'bitcode_symbols'"

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_rust#1963]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3007#0187f988-0bf7-4f57-bdb5-b2d198459037

Platform : MacOS

Error logs :  

```
ERROR: /Users/buildkite/builds/bk-imacpro-12/bazel-downstream-projects/rules_rust/examples/ios/BUILD.bazel:34:16: in ios_application rule //:ios_app:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/101969303114ba051eef48a9da14c98e/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 180, column 66, in _ios_application_impl
		debug_outputs = linking_support.debug_outputs_by_architecture(link_result.outputs)
	File "/private/var/tmp/_bazel_buildkite/101969303114ba051eef48a9da14c98e/external/build_bazel_rules_apple/apple/internal/linking_support.bzl", line 45, column 68, in _debug_outputs_by_architecture
		bitcode_symbol_maps[link_output.architecture] = link_output.bitcode_symbols
Error: 'apple_linking_output' value has no field or method 'bitcode_symbols'
Available attributes: architecture, binary, dsym_binary, environment, linkmap, platform
(06:05:42) ERROR: /Users/buildkite/builds/bk-imacpro-12/bazel-downstream-projects/rules_rust/examples/ios/BUILD.bazel:34:16: Analysis of target '//:ios_app' failed
(06:05:42) ERROR: Analysis of target '//:ios_app' failed; build aborted:


```
Steps to reproduce : 

```
 git clone https://github.com/bazelbuild/rules_rust.git
 git reset a2a1109dc8d9611bd8ea24148abaa7fbdb81d732 --hard 
 cd examples/ios
 export USE_BAZEL_VERSION=28bfb19135757bb244aa98d67bc6a42bd83364ed
 bazel build //...
```

**Fix** : Upgrade to the latest rules_apple to fix the above error, where rules_apple already fixed https://github.com/bazelbuild/rules_apple/issues/1956

Culprit : https://github.com/bazelbuild/bazel/commit/37b8e1b37d5676b3d047b528149546bf2bfefdd1

CC @meteorcloudy , @fweikert

**Comment by keith** [comment]
i'll make a new release so we don't have to pin this to a sha

**Comment by keith** [comment]
fix here https://github.com/bazelbuild/rules_rust/pull/1972 it probably won't pass if we test on bazel 5.x still but in that case we can just disable this test for older versions
