### ISSUE TITLE
Error when using crate_universe's  `all_crate_deps` for targets with platform-specific dependencies

### ISSUE THREAD

**Issue by k1nkreet** [bazelbuild/rules_rust#1994]
I'm trying to bazelify cargo workspace with `crates_repository` and for every crate with platform-specific dependencies  I'm getting the error:
```
ERROR: Traceback (most recent call last):
        File ".../crates/some-crate/BUILD.bazel", line 9, column 22, in <toplevel>
                aliases = aliases(),
        File ".../external/crate_index/defs.bzl", line 281, column 30, in aliases
                if condition_triples in crate_aliases:
Error: unhashable type: 'list'
```

After the first look at the code I've found [_CONDITIONS dict contains list items](https://github.com/bazelbuild/rules_rust/blob/main/crate_universe/3rdparty/crates/defs.bzl#L448-L487) which then used as a [key in `selects.with_or` dict](https://github.com/bazelbuild/rules_rust/blob/7073146f831f1a94dfdf7f7f6d046ae01c1c9f55/crate_universe/3rdparty/crates/defs.bzl#L205)

Here is the small repo reproducing this issue: https://github.com/k1nkreet/crate_universe_conditional_deps

**Comment by k1nkreet** [comment]
Duplicates #1880
