### ISSUE TITLE
v0.27.0 issue – Error in instrumented_files_info: private API only for use in builtins

### ISSUE THREAD

**Issue by QuentinPerez** [bazelbuild/rules_rust#2147]
Just upgraded rules_rust from v0.26 and I got this error.

```ERROR: /private/var/tmp/_bazel_quentinperez/e75744411739bef331d606bc869abdf6/rules_xcodeproj.noindex/build_output_base/external/rules_rust/util/process_wrapper/BUILD.bazel:6:36: in rust_binary_without_process_wrapper rule @rules_rust//util/process_wrapper:process_wrapper:
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_quentinperez/e75744411739bef331d606bc869abdf6/rules_xcodeproj.noindex/build_output_base/external/rules_rust/rust/private/rust.bzl", line 342, column 32, in _rust_binary_impl
                return rustc_compile_action(
        File "/private/var/tmp/_bazel_quentinperez/e75744411739bef331d606bc869abdf6/rules_xcodeproj.noindex/build_output_base/external/rules_rust/rust/private/rustc.bzl", line 1417, column 48, in rustc_compile_action
                coverage_common.instrumented_files_info(
Error in instrumented_files_info: private API only for use in builtins
```

Is it something new ?

**Comment by scentini** [comment]
Which Bazel version are you using?

**Comment by QuentinPerez** [comment]
`Build label: 7.0.0-pre.20230123.5`

**Comment by QuentinPerez** [comment]
it works with bazel 6.3.2

**Comment by qzmfranklin** [comment]
Reproduced the same error message with Bazel `7.0.0-pre.20230502.1`:

```text
/code cl/zhongming.qu/rust-wasm wip !13                                                                            09:00:53
❯ bb  test tools/build_defs/rust/examples/hello_world/...
INFO: Invocation ID: 307bab12-6fcb-4940-befa-da32155285de
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/307bab12-6fcb-4940-befa-da32155285de
ERROR: /.cache/zhongming.qu/bazel/_bazel_zhongming.qu/933c2f549343e099e3a6911b282cb71c/external/rules_rust/util/process_wrapper/BUILD.bazel:6:36: in rust_binary_without_process_wrapper rule @rules_rust//util/process_wrapper:process_wrapper: 
Traceback (most recent call last):
        File "/.cache/zhongming.qu/bazel/_bazel_zhongming.qu/933c2f549343e099e3a6911b282cb71c/external/rules_rust/rust/private/rust.bzl", line 342, column 32, in _rust_binary_impl
                return rustc_compile_action(
        File "/.cache/zhongming.qu/bazel/_bazel_zhongming.qu/933c2f549343e099e3a6911b282cb71c/external/rules_rust/rust/private/rustc.bzl", line 1417, column 48, in rustc_compile_action
                coverage_common.instrumented_files_info(
Error in instrumented_files_info: private API only for use in builtins
ERROR: /.cache/zhongming.qu/bazel/_bazel_zhongming.qu/933c2f549343e099e3a6911b282cb71c/external/rules_rust/util/process_wrapper/BUILD.bazel:6:36: Analysis of target '@rules_rust//util/process_wrapper:process_wrapper' failed
WARNING: errors encountered while analyzing target '//tools/build_defs/rust/examples/hello_world:hello_world_doc': it will not be built
WARNING: errors encountered while analyzing target '//tools/build_defs/rust/examples/hello_world:hello_world': it will not be built
INFO: Analyzed 2 targets (34 packages loaded, 6519 targets configured).
INFO: Found 0 test targets...
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 2.850s ⏳, Critical Path: 0.00s ⏰
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully ❌
ERROR: No test targets were found, yet testing was requested
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/307bab12-6fcb-4940-befa-da32155285de
```

Trying it out with Bazel `6.3.2.` fixes the problem.

This sounds like a **BIG** problem as it blocks `rules_rust` from moving onto future Bazel releases.

**Comment by scentini** [comment]
@c-mita could you PTAL, as it's `coverage` API related?
My 2 minutes research led me to https://github.com/bazelbuild/bazel/commit/c449a8211039f9145c111daa4697721ecbe18dec, which might or might not be relevant.
