### ISSUE TITLE
incompatible_depset_is_not_iterable

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_rust#218]
The code doesn't build with the Bazel flag `incompatible_depset_is_not_iterable`.
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/88#e19de0c9-aaae-4133-a716-8dd7ec196ab1

Can you take a look?

```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-hgjq/bazel-downstream-projects/rules_rust/examples/ffi/rust_calling_c/simple/BUILD:9:1: in rust_bindgen rule //ffi/rust_calling_c/simple:simple_bindgen__bindgen:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-hgjq/bazel-downstream-projects/rules_rust/examples/ffi/rust_calling_c/simple/BUILD", line 9
  | rust_bindgen(name = 'simple_bindgen__bindgen')
  | File "/home/bazel/.cache/bazel/_bazel_bazel/fb2b6638d8f3360bcf71c8bff143e163/external/io_bazel_rules_rust/bindgen/bindgen.bzl", line 48, in _rust_bindgen_impl
  | header not in cc_lib[CcInfo].compilation_context.headers
  | argument of type 'depset' is not iterable. in operator only works on lists, tuples, dicts and strings. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
```

**Comment by laurentlb** [comment]
Despite @m3rcuriel change, there are still some issues:

```
$ bazel build ... @docs//... @examples//... --incompatible_depset_is_not_iterable --nobuild 
...
	File "/usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/39ab26bd055802b7074252d4b2a2c75b/external/io_bazel_rules_rust/bindgen/bindgen.bzl", line 111, in ":".join
		[f.dirname for f in get_libs_for_static_executable(libstdcxx)]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
```
