### ISSUE TITLE
Can't cross-compile to linux with bzlmod

### ISSUE THREAD

**Issue by aran** [bazelbuild/rules_rust#2443]
Adding to `rust.toolchain` the following `extra_target_triples`

```
extra_target_triples = [
    "x86_64-unknown-linux-gnu",
],
```

causes ```Error in repository_rule: A repo named rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools is already generated by this module extension```

repro `MODULE.bazel`:

```
bazel_dep(name = "rules_rust", version = "0.38.0")

####
# rules_rust
####

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = [
        "1.75.0",
    ],
    extra_target_triples = [
        "x86_64-unknown-linux-gnu",
    ],
)
use_repo(
    rust,
    "rust_toolchains",
)

register_toolchains("@rust_toolchains//:all")
```

`hello_world/src/bin/main.rs`:
```
fn main() {
    println!("Hello, world!");
}
```

`hello_world/BUILD.bazel`:
```
load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "hello_world",
    srcs = ["src/bin/main.rs"],
)
```

`bazel run //hello_world` full error:

```
ERROR: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_aran/5397c754243baff08543b96bceec2053/external/rules_rust~0.38.0/rust/extensions.bzl", line 97, column 33, in _rust_impl
                rust_register_toolchains(
        File "/private/var/tmp/_bazel_aran/5397c754243baff08543b96bceec2053/external/rules_rust~0.38.0/rust/repositories.bzl", line 221, column 14, in rust_register_toolchains
                maybe(
        File "/private/var/tmp/_bazel_aran/5397c754243baff08543b96bceec2053/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 240, column 18, in maybe
                repo_rule(name = name, **kwargs)
        File "/private/var/tmp/_bazel_aran/5397c754243baff08543b96bceec2053/external/rules_rust~0.38.0/rust/repositories.bzl", line 981, column 61, in rust_repository_set
                all_toolchain_names.append(rust_toolchain_repository(
        File "/private/var/tmp/_bazel_aran/5397c754243baff08543b96bceec2053/external/rules_rust~0.38.0/rust/repositories.bzl", line 564, column 36, in rust_toolchain_repository
                rust_toolchain_tools_repository(
Error in repository_rule: A repo named rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools is already generated by this module extension at /private/var/tmp/_bazel_aran/5397c754243baff08543b96bceec2053/external/rules_rust~0.38.0/rust/repositories.bzl:564:36
ERROR: Analysis of target '//hello_world:hello_world' failed; build aborted: error evaluating module extension rust in @@rules_rust~0.38.0//rust:extensions.bzl
```

**Comment by AmeliasCode** [comment]
Relevant PR? https://github.com/bazelbuild/rules_rust/pull/2419

**Comment by cameron-martin** [comment]
Looks like this is fixed by the above PR, which is now merged
