### ISSUE TITLE
[Bazel CI] Error: 'struct' value has no field or method 'to_json'


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_rust#2580]
CI: https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/1993#018e7e82-1a60-47b3-9288-2291a222d273

Platform: MacOS

Logs:

```
(07:08:36) ERROR: /Users/buildkite/builds/bk-imacpro-19/bazel-org-repo-root/rules_rust/examples/ios/BUILD.bazel:27:16: in ios_application rule //:ios_app:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/8ae285ec1d4c65332096f0cfd7a30045/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 219, column 61, in _ios_application_impl
		entitlements = entitlements_support.process_entitlements(
	File "/private/var/tmp/_bazel_buildkite/8ae285ec1d4c65332096f0cfd7a30045/external/build_bazel_rules_apple/apple/internal/entitlements_support.bzl", line 308, column 26, in _process_entitlements
		content = control.to_json(),
Error: 'struct' value has no field or method 'to_json'
```

Culprit: https://github.com/bazelbuild/bazel/issues/19465#issuecomment-1997617443

Steps:

```
 git clone https://github.com/bazelbuild/rules_rust
git reset 98fab85a713a67e804a299dfe57a02deb9790ca1  --hard
export USE_BAZEL_VERSION=53857efe918b79b38a58578b29edf8f3ba378426
bazel build //... 
```

CC Greenteam @mai93

**Comment by sgowroji** [comment]
CC @c-mita

**Comment by c-mita** [comment]
Yes, but unfortunately I don't think there's a release yet that contains https://github.com/bazelbuild/rules_apple/pull/2433.

I'm not familiar with their release procedure so I don't know how long it'll be before this can be fixed.
