### ISSUE TITLE
Build failures for Android CI jobs

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#2588]
https://buildkite.com/bazel/rules-rust-rustlang/builds/11004#018e8c50-b78b-4711-89ea-8b7c825dee5c
```
bazel --nosystem_rc --nohome_rc info
ERROR: error loading package '': Label '@@platforms//host:extension.bzl' is invalid because 'host' is not a package; perhaps you meant to put the colon here: '@@platforms//:host/extension.bzl'?
Traceback (most recent call last):
  File "bazelci.py", line 4434, in <module>
    sys.exit(main())
  File "bazelci.py", line 4402, in main
    execute_commands(
  File "bazelci.py", line 1330, in execute_commands
    bazel_version = print_bazel_version_info(bazel_binary, platform)
  File "bazelci.py", line 1622, in print_bazel_version_info
    execute_command(
  File "bazelci.py", line 2709, in execute_command
    return subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--nosystem_rc', '--nohome_rc', 'info']' returned non-zero exit status 1.
🚨 Error: The command exited with status 1
```

**Comment by UebelAndre** [comment]
cc @meteorcloudy @scentini

**Comment by UebelAndre** [comment]
I think https://github.com/bazelbuild/rules_rust/pull/2589 might resolve it for us but this still looks like something broke upstream.
