### ISSUE TITLE
ARM cross compile cycle error

### ISSUE THREAD

**Issue by afking** [bazelbuild/rules_rust#267]
Trying to cross compile a hello world example binary from macOS to linux arm. Getting the error below:

```
$ bazel build :hello --platforms=@io_bazel_rules_rust//rust/platform:arm
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/private/var/tmp/_bazel_edward/3ef1b272479f90ee9043d09f4412b229/command.profile.gz'
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: topLevelKey: //:hello BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04] false
alreadyReported: false
path to cycle:
//:hello BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04] false
Key{configurationKey=BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04], requiredToolchainTypeLabels=[@io_bazel_rules_rust//rust:toolchain, @bazel_tools//tools/cpp:toolchain_type], execConstraintLabels=[], shouldSanityCheckConfiguration=false}
cycle:
@io_bazel_rules_rust//rust/platform:arm BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04] false
Key{configurationKey=BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04], requiredToolchainTypeLabels=[], execConstraintLabels=[], shouldSanityCheckConfiguration=false}

[com.google.devtools.build.lib.skyframe.TransitiveTargetCycleReporter@46468122, com.google.devtools.build.lib.skyframe.ActionArtifactCycleReporter@78a9b545, com.google.devtools.build.lib.skyframe.ConfiguredTargetCycleReporter@233a235a, com.google.devtools.build.lib.skyframe.TestSuiteCycleReporter@571a3df9, com.google.devtools.build.lib.skyframe.RegisteredToolchainsCycleReporter@25a7e9a9, com.google.devtools.build.lib.skyframe.SkylarkModuleCycleReporter@109163c5]
        at com.google.devtools.build.skyframe.CyclesReporter.maybeReportCycle(CyclesReporter.java:87)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:74)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:532)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:442)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:401)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:540)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:596)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:647)
        at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 2.137s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (7 packages loaded, 7 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: topLevelKey: //:hello BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04] false
alreadyReported: false
path to cycle:
//:hello BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04] false
Key{configurationKey=BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04], requiredToolchainTypeLabels=[@io_bazel_rules_rust//rust:toolchain, @bazel_tools//tools/cpp:toolchain_type], execConstraintLabels=[], shouldSanityCheckConfiguration=false}
cycle:
@io_bazel_rules_rust//rust/platform:arm BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04] false
Key{configurationKey=BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04], requiredToolchainTypeLabels=[], execConstraintLabels=[], shouldSanityCheckConfiguration=false}

[com.google.devtools.build.lib.skyframe.TransitiveTargetCycleReporter@46468122, com.google.devtools.build.lib.skyframe.ActionArtifactCycleReporter@78a9b545, com.google.devtools.build.lib.skyframe.ConfiguredTargetCycleReporter@233a235a, com.google.devtools.build.lib.skyframe.TestSuiteCycleReporter@571a3df9, com.google.devtools.build.lib.skyframe.RegisteredToolchainsCycleReporter@25a7e9a9, com.google.devtools.build.lib.skyframe.SkylarkModuleCycleReporter@109163c5]
        at com.google.devtools.build.skyframe.CyclesReporter.maybeReportCycle(CyclesReporter.java:87)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:74)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:532)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:442)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:401)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:540)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:596)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:647)
        at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: topLevelKey: //:hello BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04] false
alreadyReported: false
path to cycle:
//:hello BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04] false
Key{configurationKey=BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04], requiredToolchainTypeLabels=[@io_bazel_rules_rust//rust:toolchain, @bazel_tools//tools/cpp:toolchain_type], execConstraintLabels=[], shouldSanityCheckConfiguration=false}
cycle:
@io_bazel_rules_rust//rust/platform:arm BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04] false
Key{configurationKey=BuildConfigurationValue.Key[9a8e1270212d6a881ea428e601fded04], requiredToolchainTypeLabels=[], execConstraintLabels=[], shouldSanityCheckConfiguration=false}

[com.google.devtools.build.lib.skyframe.TransitiveTargetCycleReporter@46468122, com.google.devtools.build.lib.skyframe.ActionArtifactCycleReporter@78a9b545, com.google.devtools.build.lib.skyframe.ConfiguredTargetCycleReporter@233a235a, com.google.devtools.build.lib.skyframe.TestSuiteCycleReporter@571a3df9, com.google.devtools.build.lib.skyframe.RegisteredToolchainsCycleReporter@25a7e9a9, com.google.devtools.build.lib.skyframe.SkylarkModuleCycleReporter@109163c5]
        at com.google.devtools.build.skyframe.CyclesReporter.maybeReportCycle(CyclesReporter.java:87)
        at com.google.devtools.build.skyframe.CyclesReporter.reportCycles(CyclesReporter.java:74)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.processErrors(SkyframeBuildView.java:532)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:442)
        at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:401)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
        at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:124)
        at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
        at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
        at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:540)
        at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
        at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:596)
        at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:647)
```

Project is at master:
```
http_archive(
    name = "io_bazel_rules_rust",
    sha256 = "69b67e19532b12da3edccda404772e85a788d16ae739343f5338dd340a0fba2e",
    strip_prefix = "rules_rust-ec436b5ff2ab1ddeba6f27a7a1a5d263812981a6",
    urls = [
        # Master branch as of 2019-11-10
        "https://github.com/bazelbuild/rules_rust/archive/ec436b5ff2ab1ddeba6f27a7a1a5d263812981a6.tar.gz",
    ],
)
```

**Comment by m3rcuriel** [comment]
So your issue is that `@io_bazel_rules_rust//rust/platform:arm` is not a platform, it is a `config_setting`.

Also, upstream Bazel afaict has a bug where it has decided to throw this monster error when you provide a `config_setting` to `--platforms`. I'll report it there.

**Comment by afking** [comment]
@m3rcuriel Thanks!
