### ISSUE TITLE
[Bazel CI] rust_project_json_test test is failing at Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_rust#2712]
CI: https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/2081#019043b1-532a-4412-8724-970820f22fa2

 Platform: Ubuntu

 Logs: 
```

FAIL: //:rust_project_json_test (Exit 101) (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/3eff4e64900a73edcbb7c9a2544ec0e2/execroot/_main/bazel-out/k8-fastbuild/testlogs/rust_project_json_test/test.log)
INFO: From Testing //:rust_project_json_test:
==================== Test output for //:rust_project_json_test:
running 2 tests
test tests::test_aliases_are_applied ... FAILED
test tests::test_aspect_traverses_all_the_right_corners_of_target_graph ... ok
failures:
---- tests::test_aliases_are_applied stdout ----
thread 'tests::test_aliases_are_applied' panicked at rust_project_json_test.rs:62:9:
assertion `left == right` failed
  left: "renamed_proc_macro_dep"
 right: "shorter_name"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    tests::test_aliases_are_applied
test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_rust
git reset c014c618f950f80edc09330c834f30d20b7589f8  --hard
export USE_BAZEL_VERSION=8d188388cb3f9a5d4252b3f07832fff6c819422c
bazel run --show_progress_rate_limit=5 --curses=yes --color=yes --terminal_columns=143 --show_timestamps --verbose_failures --jobs=30 --announce_rc --experimental_repository_cache_hardlinks --disk_cache= --sandbox_tmpfs_path=/tmp //test/rust_analyzer:rust_analyzer_test 
 ``` 
 CC Greenteam @fweikert

**Comment by illicitonion** [comment]
I tried to repro in the same docker image and couldn't.

**Comment by sgowroji** [comment]
Able to reproduce 
```

sgowroji-macbookpro3:rules_rust sgowroji$ git clone -v https://github.com/bazelbuild/rules_rust.git 
Cloning into 'rules_rust'...
POST git-upload-pack (196 bytes)
POST git-upload-pack (gzip 3223 to 1637 bytes)
remote: Enumerating objects: 43529, done.
remote: Counting objects: 100% (13095/13095), done.
remote: Compressing objects: 100% (918/918), done.
remote: Total 43529 (delta 12594), reused 12206 (delta 12177), pack-reused 3043
Receiving objects: 100% (43529/43529), 18.04 MiB | 7.12 MiB/s, done.
Resolving deltas: 100% (34646/34646), done.
sgowroji-macbookpro3:rules_rust sgowroji$ cd rules*
sgowroji-macbookpro3:rules_rust sgowroji$ ls
ARCHITECTURE.md		README.md		proto
AUTHORS			WORKSPACE.bazel		rust
BUILD.bazel		bindgen			test
CODEOWNERS		cargo			tools
COMPATIBILITY.md	crate_universe		util
CONTRIBUTING.md		docs			version.bzl
CONTRIBUTORS		examples		wasm_bindgen
LICENSE.txt		ffi
MODULE.bazel		nix
sgowroji-macbookpro3:rules_rust sgowroji$ 
sgowroji-macbookpro3:rules_rust sgowroji$ git reset c014c618f950f80edc09330c834f30d20b7589f8 --hard
HEAD is now at c014c618 crate_universe docs: Split bzlmod from workspace (#2700)
sgowroji-macbookpro3:rules_rust sgowroji$ export USE_BAZEL_VERSION=8d188388cb3f9a5d4252b3f07832fff6c819422c
sgowroji-macbookpro3:rules_rust sgowroji$ ls
ARCHITECTURE.md		README.md		proto
AUTHORS			WORKSPACE.bazel		rust
BUILD.bazel		bindgen			test
CODEOWNERS		cargo			tools
COMPATIBILITY.md	crate_universe		util
CONTRIBUTING.md		docs			version.bzl
CONTRIBUTORS		examples		wasm_bindgen
LICENSE.txt		ffi
MODULE.bazel		nix
sgowroji-macbookpro3:rules_rust sgowroji$ bazel run --show_progress_rate_limit=5 --curses=yes --color=yes --terminal_columns=143 --show_timestamps --verbose_failures --jobs=30 --announce_rc --experimental_repository_cache_hardlinks --disk_cache= --sandbox_tmpfs_path=/tmp //test/rust_analyzer:rust_analyzer_test
2024/06/25 11:25:23 Using unreleased version at commit 8d188388cb3f9a5d4252b3f07832fff6c819422c
2024/06/25 11:25:23 Downloading https://storage.googleapis.com/bazel-builds/artifacts/macos/8d188388cb3f9a5d4252b3f07832fff6c819422c/bazel...
Extracting Bazel installation...
rulesStarting local Bazel server and connecting to it...
(11:25:41) INFO: Reading 'startup' options from /Users/sgowroji/bazelci/rules_rust/rules_rust/.bazelrc: --windows_enable_symlinks
(11:25:41) INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
(11:25:41) INFO: Reading rc options for 'run' from /Users/sgowroji/bazelci/rules_rust/rules_rust/.bazelrc:
  Inherited 'common' options: --enable_platform_specific_config --experimental_cc_shared_library --noenable_bzlmod --lockfile_mode=off
(11:25:41) INFO: Reading rc options for 'run' from /Users/sgowroji/bazelci/rules_rust/rules_rust/.bazelrc:
  Inherited 'build' options: --incompatible_disallow_empty_glob=true --nolegacy_external_runfiles --incompatible_merge_fixed_and_default_shell_env
(11:25:41) INFO: Current date is 2024-06-25
(11:25:46) Computing main repo mapping: 
(11:25:51) Computing main repo mapping: 
(11:25:56) Computing main repo mapping: 
(11:26:01) Computing main repo mapping: 
(11:26:06) Computing main repo mapping: 
(11:26:11) Computing main repo mapping: 
(11:26:16) Computing main repo mapping: 
(11:26:21) Computing main repo mapping: 
(11:26:26) Computing main repo mapping: 
(11:26:31) Computing main repo mapping: 
(11:26:36) Computing main repo mapping: 
(11:26:46) Computing main repo mapping: 
(11:26:48) Analyzing: target //test/rust_analyzer:rust_analyzer_test (1 packages(11:26:48) Analyzing: target //test/rust_analyzer:rust_analyzer_test (1 packages(11:26:56) Analyzing: target //test/rust_analyzer:rust_analyzer_test (108 packag(11:27:01) Analyzing: target //test/rust_analyzer:rust_analyzer_test (108 packag(11:27:04) INFO: Analyzed target //test/rust_analyzer:rust_analyzer_test (113 packages loaded, 304 targets configured).
(11:27:05) INFO: Found 1 target...
Target //test/rust_analyzer:rust_analyzer_test up-to-date:
  bazel-bin/test/rust_analyzer/rust_analyzer_test
(11:27:05) INFO: Elapsed time: 91.418s, Critical Path: 0.31s
(11:27:05) INFO: 5 processes: 5 internal.
(11:27:05) INFO: Build completed successfully, 5 total actions
(11:27:05) INFO: Running command line: bazel-bin/test/rust_analyzer/rust_analyzer_test test/rust_analyzer
Generated workspace: /var/folders/6n/fgcyj4396kqfvfq1fqyy6fl400j1bb/T/rules_rust_test_rust_analyzer-XXXXXXXXXX.HtgYypnERR/rules_rust_test_rust_analyzer
Testing 'aspect_traversal_test'
Generating rust-project.json...
Starting local Bazel server and connecting to it...
WARNING: --enable_bzlmod is set, but no MODULE.bazel file was found at the workspace root. Bazel will create an empty MODULE.bazel file. Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel. For more details, please refer to https://github.com/bazelbuild/bazel/issues/18958.
INFO: Analyzed target @@rules_rust//tools/rust_analyzer:gen_rust_project (198 packages loaded, 4672 targets configured).
INFO: Found 1 target...
Target @@rules_rust//tools/rust_analyzer:gen_rust_project up-to-date:
  bazel-bin/external/rules_rust/tools/rust_analyzer/gen_rust_project
INFO: Elapsed time: 132.116s, Critical Path: 35.44s
INFO: 190 processes: 126 internal, 64 darwin-sandbox.
INFO: Build completed successfully, 190 total actions
INFO: Running command line: bazel-bin/external/rules_rust/tools/rust_analyzer/gen_rust_project
Building...
INFO: Analyzed 14 targets (0 packages loaded, 0 targets configured).
INFO: Found 14 targets...
INFO: Elapsed time: 18.174s, Critical Path: 17.75s
INFO: 46 processes: 16 internal, 30 darwin-sandbox.
INFO: Build completed successfully, 46 total actions
Testing...
INFO: Analyzed 14 targets (0 packages loaded, 0 targets configured).
FAIL: //:rust_project_json_test (Exit 101) (see /private/var/tmp/_bazel_sgowroji/1c829bad9a4f837350fdd284ebcee1e8/execroot/_main/bazel-out/darwin_x86_64-fastbuild/testlogs/rust_project_json_test/test.log)
INFO: From Testing //:rust_project_json_test:
==================== Test output for //:rust_project_json_test:

running 2 tests
test tests::test_aliases_are_applied ... FAILED
test tests::test_aspect_traverses_all_the_right_corners_of_target_graph ... ok

failures:

---- tests::test_aliases_are_applied stdout ----
thread 'tests::test_aliases_are_applied' panicked at rust_project_json_test.rs:62:9:
assertion `left == right` failed
  left: "renamed_proc_macro_dep"
 right: "shorter_name"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_aliases_are_applied

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

================================================================================
INFO: Found 12 targets and 2 test targets...
INFO: Elapsed time: 1.009s, Critical Path: 0.84s
INFO: 3 processes: 4 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 3 total actions
//:mylib_test                                                            PASSED in 0.4s
//:rust_project_json_test                                                FAILED in 0.7s
  /private/var/tmp/_bazel_sgowroji/1c829bad9a4f837350fdd284ebcee1e8/execroot/_main/bazel-out/darwin_x86_64-fastbuild/testlogs/rust_project_json_test/test.log

Executed 2 out of 2 tests: 1 test passes and 1 fails locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
sgowroji-macbookpro3:rules_rust sgowroji$ rules

```

**Comment by sgowroji** [comment]
Hello @illicitonion, Did you get a chance to check the above failures ?

**Comment by deepalak56** [comment]
Since the rules_rust repo has been disabled from Bazel CI, we are closing this issue.
