### ISSUE TITLE
regression in 0.48.0 when compiling protobuf

### ISSUE THREAD

**Issue by pdeva** [bazelbuild/rules_rust#2762]
getting this error after upgrading from `0.47.1` to `0.48.0`

```
ERROR: /home/pdeva/code/monorepo/schema/proto/qu/storage/v1/BUILD:6:14: in @@rules_rust~//proto/prost/private:prost.bzl%rust_prost_aspect aspect on proto_library rule //schema/proto/qu/storage/v1:storage_proto:
Traceback (most recent call last):
	File "/home/pdeva/.cache/bazel/_bazel_pdeva/b1a4ac6988a94eb0ad1222a792d4139b/external/rules_rust~/proto/prost/private/prost.bzl", line 240, column 47, in _rust_prost_aspect_impl
		lib_rs, package_info_file = _compile_proto(
	File "/home/pdeva/.cache/bazel/_bazel_pdeva/b1a4ac6988a94eb0ad1222a792d4139b/external/rules_rust~/proto/prost/private/prost.bzl", line 54, column 35, in _compile_proto
		tools = depset([proto_compiler.executable])
Error: <target @@protobuf~//:protoc> (rule 'cc_binary') doesn't have provider 'executable'
ERROR: Analysis of target '//schema/proto/qu/storage/v1:storage_proto' failed
```

relevant bazelmod config:

```starlark
bazel_dep(name = "protobuf", version = "27.2", repo_name = "com_google_protobuf")
bazel_dep(name = "rules_proto", version = "6.0.2")
bazel_dep(name = "rules_rust", version = "0.48.0")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.79.0"],
)

use_repo(rust, "rust_toolchains")
register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
crate.from_cargo(
    name = "crate_index",
    cargo_lockfile = "//:Cargo.lock",
    manifests = [
        "//:Cargo.toml",
        "//schema/proto:Cargo.toml",
        "//examples/rust/helloworld:Cargo.toml",        
    ],
)
use_repo(crate, "crate_index")
crate.spec(
    package = "protoc-gen-prost",
    version = "0.3.1",
)
crate.spec(
    package = "protoc-gen-tonic",
    version = "0.4.0",
)
crate.from_specs(
    name = "crate_specs",
    generate_binaries = True,
)
use_repo(crate, "crate_specs")
register_toolchains("//:prost_toolchain")
```

**Comment by pdeva** [comment]
seems this can be fixed by removing `proto_compiler` attrib from `rust_prost_toolchain`
