### ISSUE TITLE
prost_toolchain.proto_compiler missing files_to_run?

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/rules_rust#2800]
I'm building with rules_rust 0.49.3, bazel 6.5.0.

Using the prost toolchain with `proto_compiler = '@com_google_protobuf//:protoc`. Got the following error:

```text
ERROR: /code/tools/build_defs/rust/examples/proto/helloworld/api/BUILD.bazel:4:14: in @rules_rust//proto/prost/private:prost.bzl%rust_prost_aspect aspect on proto_library rule //tools/build_defs/rust/examples/proto/helloworld/api:api_proto: 
Traceback (most recent call last):
        File "/.cache/quzhongming/bazel/_bazel_quzhongming/933c2f549343e099e3a6911b282cb71c/external/rules_rust/proto/prost/private/prost.bzl", line 243, column 47, in _rust_prost_aspect_impl
                lib_rs, package_info_file = _compile_proto(
        File "/.cache/quzhongming/bazel/_bazel_quzhongming/933c2f549343e099e3a6911b282cb71c/external/rules_rust/proto/prost/private/prost.bzl", line 57, column 35, in _compile_proto
                tools = depset([proto_compiler.executable])
Error: <target @com_google_protobuf//:protoc> (rule 'cc_binary') doesn't have provider 'executable'
```

Debugged a while, and found that the following patch solves the problem:

```diff
diff --git a/proto/prost/private/prost.bzl b/proto/prost/private/prost.bzl
index c3a7d4e..03f0837 100644
--- a/proto/prost/private/prost.bzl
+++ b/proto/prost/private/prost.bzl
@@ -50,7 +50,7 @@ def _compile_proto(ctx, crate_name, proto_info, deps, prost_toolchain, rustfmt_t
     package_info_file = ctx.actions.declare_file(ctx.label.name + ".prost_package_info")
     lib_rs = ctx.actions.declare_file("{}.lib.rs".format(ctx.label.name))
 
-    proto_compiler = prost_toolchain.proto_compiler
+    proto_compiler = prost_toolchain.proto_compiler.files_to_run
     tools = depset([proto_compiler.executable])
 
     additional_args = ctx.actions.args()
```

Is this a bug or am I using it wrong? 
```

**Comment by UebelAndre** [comment]
This should be resolved by https://github.com/bazelbuild/rules_rust/pull/2794
