### ISSUE TITLE
Allow configuring digests to fail sometimes.

### ISSUE THREAD

**Issue by Zemnmez** [bazelbuild/rules_rust#2915]
I run a script that automatically fixes generated commits, and the script is checked into my Bazel workspace. In the case of rules_rust, it will automagically fix the digests in the lockfile. However, I am unable to run it because currently if any digest is incorrect, bazel fails all builds regardless of if the build artifact used rust or not:

```
ommand failed: npx --yes @bazel/bazelisk run //ci:postupgrade
INFO: Invocation ID: a367b2b1-aff3-4f10-9c65-f6aa590fc2b9
Computing main repo mapping: 
INFO: Repository cargo instantiated at:
  /tmp/renovate/repos/github/zemn-me/monorepo/WORKSPACE:45:18: in <toplevel>
Repository rule crates_repository defined at:
  /opt/containerbase/cache/bazel/_bazel_ubuntu/e7aba95ef79b2dab8608435d3191c63a/external/rules_rust/crate_universe/private/crates_repository.bzl:108:36: in <toplevel>
INFO: repository @@cargo' used the following cache hits instead of downloading the corresponding file.
 * Hash '7ec5837a46305a71560d5bb051abaa12d968c8cbea0a39922a3b575bdc50c3ac' for https://github.com/bazelbuild/rules_rust/releases/download/0.51.0/cargo-bazel-x86_64-unknown-linux-gnu
If the definition of 'repository @@cargo' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'cargo':
   Traceback (most recent call last):
	File "/opt/containerbase/cache/bazel/_bazel_ubuntu/e7aba95ef79b2dab8608435d3191c63a/external/rules_rust/crate_universe/private/crates_repository.bzl", line 45, column 28, in _crates_repository_impl
		repin = determine_repin(
	File "/opt/containerbase/cache/bazel/_bazel_ubuntu/e7aba95ef79b2dab8608435d3191c63a/external/rules_rust/crate_universe/private/generate_utils.bzl", line 422, column 13, in determine_repin
		fail(msg)
Error in fail: Error: Digests do not match: Current Digest("84d8680eb4b4a6a748c837cd6a6362f0529f572b2b702b202b9f6747e5339299") != Expected Digest("062f4cf25f283a570240a29558175f1b0bf8db58fcff9a5b58f1529c13ee59d6")

The current `lockfile` is out of date for 'cargo'. Please re-run bazel using `CARGO_BAZEL_REPIN=true` if this is expected and the lockfile should be updated.
ERROR: Error computing the main repository mapping: no such package '@@cargo//': Error: Digests do not match: Current Digest("84d8680eb4b4a6a748c837cd6a6362f0529f572b2b702b202b9f6747e5339299") != Expected Digest("062f4cf25f283a570240a29558175f1b0bf8db58fcff9a5b58f1529c13ee59d6")

The current `lockfile` is out of date for 'cargo'. Please re-run bazel using `CARGO_BAZEL_REPIN=true` if this is expected and the lockfile should be updated.
```

It would be really useful if I could set a flag like `--keep_going`, which allows builds to succeed even if the hashes are wrong for the purpose of updating the lockfile.

If I had guidance on how to do it, I'd be happy to contribute a patch myself.

**Comment by Zemnmez** [comment]
I discovered that I can `CARGO_BAZEL_REPIN=true` when running my command and it works just fine! I was under the impression it only worked for `sync` :)
