### ISSUE TITLE
build fails on bazel 8

### ISSUE THREAD

**Issue by pdeva** [bazelbuild/rules_rust#3135]
getting followin error.

version:
rules_rust "0.56.0"
bazel 8.0.0
linux x64 ubuntu 22.04

```python
bazel_dep(name = "rules_rust", version = "0.56.0")
rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.83.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
crate.from_cargo(
    name = "crate_index",
    cargo_lockfile = "//:Cargo.lock",
    manifests = [
        "//:Cargo.toml",
        "//schema/proto:Cargo.toml",
       ...],
)


use_repo(crate, "crate_index")
crate.spec(
    package = "protoc-gen-prost",
    version = "0.3.1",
)
crate.spec(
    package = "protoc-gen-tonic",
    version = "0.4.0",
)
crate.from_specs(
    name = "crate_specs",
    generate_binaries = True,
)
use_repo(crate, "crate_specs")

register_toolchains("//:prost_toolchain")

```

```
ERROR: /mnt/code/bazel/out/base/external/rules_rust+/crate_universe/extensions.bzl:363:17: Traceback (most recent call last):
        File "/mnt/code/bazel/out/base/external/rules_rust+/crate_universe/extensions.bzl", line 459, column 37, in _crate_impl
                _generate_hub_and_spokes(
        File "/mnt/code/bazel/out/base/external/rules_rust+/crate_universe/extensions.bzl", line 134, column 16, in _generate_hub_and_spokes
                cargo_bazel(splice_args)
        File "/mnt/code/bazel/out/base/external/rules_rust+/crate_universe/extensions.bzl", line 363, column 17, in run
                fail("%s returned with exit code %d:\n%s" % (pretty_args, result.return_code, result.stderr))
Error in fail: /mnt/code/bazel/out/base/modextwd/rules_rust++crate/cargo-bazel splice --output-dir /mnt/code/bazel/out/base/modextwd/rules_rust++crate/crate
_index/splicing-output --config /mnt/code/bazel/out/base/modextwd/rules_rust++crate/crate_index/config.json --splicing-manifest /mnt/code/bazel/out/base/mod
extwd/rules_rust++crate/crate_index/splicing_manifest.json --nonhermetic-root-bazel-workspace-dir /mnt/code/monorepo --cargo-lockfile /mnt/code/monorepo/Car
go.lock --cargo /mnt/code/bazel/out/base/external/rules_rust++rust_host_tools+rust_host_tools/bin/cargo --rustc /mnt/code/bazel/out/base/external/rules_rust
++rust_host_tools+rust_host_tools/bin/rustc returned with exit code 1:
Error: Failed to splice workspace

Caused by:
    Some manifests are not being tracked.
    Please add the following labels to the `manifests` key:
     //:vendor/RustyXML/Cargo.toml
     //:vendor/addr2line/Cargo.toml
     //:vendor/adler2/Cargo.toml
     //:vendor/ahash/Cargo.toml
     //:vendor/aho-corasick/Cargo.toml
     //:vendor/allocator-api2/Cargo.toml
     //:vendor/android-tzdata/Cargo.toml
     //:vendor/android_system_properties/Cargo.toml
     //:vendor/anes/Cargo.toml
     //:vendor/anstream/Cargo.toml
     //:vendor/anstyle/Cargo.toml
     //:vendor/anstyle-parse/Cargo.toml
     //:vendor/anstyle-query/Cargo.toml
     //:vendor/anstyle-wincon/Cargo.toml
     //:vendor/anyhow/Cargo.toml
     //:vendor/ascii/Cargo.toml
     //:vendor/async-channel/Cargo.toml
     //:vendor/async-channel-1.9.0/Cargo.toml
     //:vendor/async-io/Cargo.toml
     //:vendor/async-lock/Cargo.toml
     //:vendor/async-stream/Cargo.toml
     //:vendor/async-stream-impl/Cargo.toml
     //:vendor/async-trait/Cargo.toml
     //:vendor/atomic/Cargo.toml
     //:vendor/atomic-waker/Cargo.toml
     //:vendor/autocfg/Cargo.toml
     //:vendor/aws-config/Cargo.toml
     //:vendor/aws-credential-types/Cargo.toml
     //:vendor/aws-lc-rs/Cargo.toml
     //:vendor/aws-lc-sys/Cargo.toml
     //:vendor/aws-runtime/Cargo.toml
     //:vendor/aws-sdk-s3/Cargo.toml
     //:vendor/aws-sdk-sso/Cargo.toml
     //:vendor/aws-sdk-ssooidc/Cargo.toml
     //:vendor/aws-sdk-sts/Cargo.toml
     //:vendor/aws-sigv4/Cargo.toml
     //:vendor/aws-smithy-async/Cargo.toml
     //:vendor/aws-smithy-checksums/Cargo.toml
     //:vendor/aws-smithy-eventstream/Cargo.toml
     //:vendor/aws-smithy-http/Cargo.toml
     //:vendor/aws-smithy-json/Cargo.toml
     //:vendor/aws-smithy-query/Cargo.toml
     //:vendor/aws-smithy-runtime/Cargo.toml
     //:vendor/aws-smithy-runtime-api/Cargo.toml
     //:vendor/aws-smithy-types/Cargo.toml
     //:vendor/aws-smithy-xml/Cargo.toml
     //:vendor/aws-types/Cargo.toml
     //:vendor/axum/Cargo.toml
     //:vendor/axum-core/Cargo.toml
     //:vendor/azure_core/Cargo.toml
     //:vendor/azure_storage/Cargo.toml
     //:vendor/azure_storage_blobs/Cargo.toml
     //:vendor/azure_svc_blobstorage/Cargo.toml
     //:vendor/backtrace/Cargo.toml
     //:vendor/base16ct/Cargo.toml
     //:vendor/base64/Cargo.toml
     //:vendor/base64-0.13.1/Cargo.toml
     //:vendor/base64-0.21.7/Cargo.toml
     //:vendor/base64-simd/Cargo.toml
     //:vendor/base64ct/Cargo.toml
     //:vendor/bincode/Cargo.toml
     //:vendor/bindgen/Cargo.toml
     //:vendor/bitflags/Cargo.toml
     //:vendor/bitflags-1.3.2/Cargo.toml
     //:vendor/block-buffer/Cargo.toml
     //:vendor/bollard/Cargo.toml
     //:vendor/bollard-stubs/Cargo.toml
     //:vendor/bumpalo/Cargo.toml
     //:vendor/bytemuck/Cargo.toml
     //:vendor/byteorder/Cargo.toml
     //:vendor/bytes/Cargo.toml
     //:vendor/bytes-utils/Cargo.toml
     //:vendor/cast/Cargo.toml
     //:vendor/cc/Cargo.toml
     //:vendor/cexpr/Cargo.toml
     //:vendor/cfg-if/Cargo.toml
     //:vendor/cfg_aliases/Cargo.toml
     //:vendor/choice/Cargo.toml
     //:vendor/chrono/Cargo.toml
     //:vendor/chunked_transfer/Cargo.toml
     //:vendor/ciborium/Cargo.toml
     //:vendor/ciborium-io/Cargo.toml
     //:vendor/ciborium-ll/Cargo.toml
     //:vendor/clang-sys/Cargo.toml
     //:vendor/clap/Cargo.toml
     //:vendor/clap_builder/Cargo.toml
     //:vendor/clap_derive/Cargo.toml
     //:vendor/clap_lex/Cargo.toml
     //:vendor/cmake/Cargo.toml
     //:vendor/colorchoice/Cargo.toml
     //:vendor/concurrent-queue/Cargo.toml
     //:vendor/const-oid/Cargo.toml
     //:vendor/convert_case/Cargo.toml
     //:vendor/core-foundation/Cargo.toml
     //:vendor/core-foundation-0.9.4/Cargo.toml
     //:vendor/core-foundation-sys/Cargo.toml
     //:vendor/cpufeatures/Cargo.toml
     //:vendor/crc/Cargo.toml
     //:vendor/crc-catalog/Cargo.toml
     //:vendor/crc32c/Cargo.toml
     //:vendor/crc32fast/Cargo.toml
     //:vendor/criterion/Cargo.toml
     //:vendor/criterion-plot/Cargo.toml
     //:vendor/crossbeam-channel/Cargo.toml
     //:vendor/crossbeam-deque/Cargo.toml
     //:vendor/crossbeam-epoch/Cargo.toml
     //:vendor/crossbeam-utils/Cargo.toml
     //:vendor/crunchy/Cargo.toml
     //:vendor/crypto-bigint/Cargo.toml
     //:vendor/crypto-bigint-0.4.9/Cargo.toml
     //:vendor/crypto-common/Cargo.toml
     //:vendor/darling/Cargo.toml
     //:vendor/darling_core/Cargo.toml
     //:vendor/darling_macro/Cargo.toml
     //:vendor/dashmap/Cargo.toml
     //:vendor/der/Cargo.toml
     //:vendor/deranged/Cargo.toml
     //:vendor/digest/Cargo.toml
     //:vendor/displaydoc/Cargo.toml
     //:vendor/docker_credential/Cargo.toml
     //:vendor/dunce/Cargo.toml
     //:vendor/dyn-clone/Cargo.toml
     //:vendor/ecdsa/Cargo.toml
     //:vendor/either/Cargo.toml
     //:vendor/elliptic-curve/Cargo.toml
     //:vendor/env_filter/Cargo.toml
     //:vendor/env_logger/Cargo.toml
     //:vendor/equivalent/Cargo.toml
     //:vendor/erased-serde/Cargo.toml
     //:vendor/errno/Cargo.toml
     //:vendor/etcetera/Cargo.toml
     //:vendor/event-listener/Cargo.toml
     //:vendor/event-listener-2.5.3/Cargo.toml
     //:vendor/event-listener-strategy/Cargo.toml
     //:vendor/fastrand/Cargo.toml
     //:vendor/fastrand-1.9.0/Cargo.toml
     //:vendor/ff/Cargo.toml
     //:vendor/filetime/Cargo.toml
     //:vendor/fixedbitset/Cargo.toml
     //:vendor/flate2/Cargo.toml
     //:vendor/fnv/Cargo.toml
     //:vendor/foca/Cargo.toml
     //:vendor/foldhash/Cargo.toml
     //:vendor/foreign-types/Cargo.toml
     //:vendor/foreign-types-shared/Cargo.toml
     //:vendor/form_urlencoded/Cargo.toml
     //:vendor/fs_extra/Cargo.toml
     //:vendor/futures/Cargo.toml
     //:vendor/futures-channel/Cargo.toml
     //:vendor/futures-core/Cargo.toml
     //:vendor/futures-executor/Cargo.toml
     //:vendor/futures-io/Cargo.toml
     //:vendor/futures-lite/Cargo.toml
     //:vendor/futures-lite-1.13.0/Cargo.toml
     //:vendor/futures-macro/Cargo.toml
     //:vendor/futures-sink/Cargo.toml
     //:vendor/futures-task/Cargo.toml
     //:vendor/futures-util/Cargo.toml
     //:vendor/generic-array/Cargo.toml
     //:vendor/getrandom/Cargo.toml
     //:vendor/getrandom-0.1.16/Cargo.toml
     //:vendor/gimli/Cargo.toml
     //:vendor/glob/Cargo.toml
     //:vendor/group/Cargo.toml
     //:vendor/h2/Cargo.toml
     //:vendor/h2-0.3.26/Cargo.toml
     //:vendor/half/Cargo.toml
     //:vendor/hashbrown/Cargo.toml
     //:vendor/hashbrown-0.12.3/Cargo.toml
     //:vendor/hashbrown-0.14.5/Cargo.toml
     //:vendor/hdrhistogram/Cargo.toml
     //:vendor/heck/Cargo.toml
     //:vendor/hermit-abi/Cargo.toml
     //:vendor/hermit-abi-0.3.9/Cargo.toml
     //:vendor/hex/Cargo.toml
     //:vendor/hmac/Cargo.toml
     //:vendor/home/Cargo.toml
     //:vendor/http/Cargo.toml
     //:vendor/http-0.2.12/Cargo.toml
     //:vendor/http-body/Cargo.toml
     //:vendor/http-body-0.4.6/Cargo.toml
     //:vendor/http-body-util/Cargo.toml
     //:vendor/http-types/Cargo.toml
     //:vendor/httparse/Cargo.toml
     //:vendor/httpdate/Cargo.toml
     //:vendor/humantime/Cargo.toml
     //:vendor/hyper/Cargo.toml
     //:vendor/hyper-0.14.32/Cargo.toml
     //:vendor/hyper-named-pipe/Cargo.toml
     //:vendor/hyper-rustls/Cargo.toml
     //:vendor/hyper-rustls-0.24.2/Cargo.toml
     //:vendor/hyper-timeout/Cargo.toml
     //:vendor/hyper-tls/Cargo.toml
     //:vendor/hyper-util/Cargo.toml
     //:vendor/hyperlocal/Cargo.toml
     //:vendor/iana-time-zone/Cargo.toml
     //:vendor/iana-time-zone-haiku/Cargo.toml
     //:vendor/icu_collections/Cargo.toml
     //:vendor/icu_locid/Cargo.toml
     //:vendor/icu_locid_transform/Cargo.toml
     //:vendor/icu_locid_transform_data/Cargo.toml
     //:vendor/icu_normalizer/Cargo.toml
     //:vendor/icu_normalizer_data/Cargo.toml
     //:vendor/icu_properties/Cargo.toml
     //:vendor/icu_properties_data/Cargo.toml
     //:vendor/icu_provider/Cargo.toml
     //:vendor/icu_provider_macros/Cargo.toml
     //:vendor/id-set/Cargo.toml
     //:vendor/ident_case/Cargo.toml
     //:vendor/idna/Cargo.toml
     //:vendor/idna_adapter/Cargo.toml
     //:vendor/indexmap/Cargo.toml
     //:vendor/indexmap-1.9.3/Cargo.toml
     //:vendor/infer/Cargo.toml
     //:vendor/instant/Cargo.toml
     //:vendor/ipnet/Cargo.toml
     //:vendor/is-terminal/Cargo.toml
     //:vendor/is_terminal_polyfill/Cargo.toml
     //:vendor/itertools/Cargo.toml
     //:vendor/itertools-0.10.5/Cargo.toml
     //:vendor/itertools-0.12.1/Cargo.toml
     //:vendor/itoa/Cargo.toml
     //:vendor/jobserver/Cargo.toml
     //:vendor/js-sys/Cargo.toml
     //:vendor/kafka-protocol/Cargo.toml
     //:vendor/lazy_static/Cargo.toml
     //:vendor/lazycell/Cargo.toml
     //:vendor/libc/Cargo.toml
     //:vendor/libloading/Cargo.toml
     //:vendor/libm/Cargo.toml
     //:vendor/libredox/Cargo.toml
     //:vendor/linux-raw-sys/Cargo.toml
     //:vendor/litemap/Cargo.toml
     //:vendor/lock_api/Cargo.toml
     //:vendor/log/Cargo.toml
     //:vendor/lru/Cargo.toml
     //:vendor/lz4/Cargo.toml
     //:vendor/lz4-sys/Cargo.toml
     //:vendor/matchers/Cargo.toml
     //:vendor/matchit/Cargo.toml
     //:vendor/md-5/Cargo.toml
     //:vendor/memchr/Cargo.toml
     //:vendor/metrics/Cargo.toml
     //:vendor/metrics-exporter-prometheus/Cargo.toml
     //:vendor/metrics-util/Cargo.toml
     //:vendor/mime/Cargo.toml
     //:vendor/minimal-lexical/Cargo.toml
     //:vendor/miniz_oxide/Cargo.toml
     //:vendor/mio/Cargo.toml
     //:vendor/multi_index_map/Cargo.toml
     //:vendor/multi_index_map_derive/Cargo.toml
     //:vendor/multimap/Cargo.toml
     //:vendor/nanoid/Cargo.toml
     //:vendor/native-tls/Cargo.toml
     //:vendor/nohash-hasher/Cargo.toml
     //:vendor/nom/Cargo.toml
     //:vendor/nu-ansi-term/Cargo.toml
     //:vendor/num-conv/Cargo.toml
     //:vendor/num-integer/Cargo.toml
     //:vendor/num-traits/Cargo.toml
     //:vendor/num_cpus/Cargo.toml
     //:vendor/object/Cargo.toml
     //:vendor/object_store/Cargo.toml
     //:vendor/once_cell/Cargo.toml
     //:vendor/oorandom/Cargo.toml
     //:vendor/openssl/Cargo.toml
     //:vendor/openssl-macros/Cargo.toml
     //:vendor/openssl-probe/Cargo.toml
     //:vendor/openssl-sys/Cargo.toml
     //:vendor/opentelemetry/Cargo.toml
     //:vendor/opentelemetry-otlp/Cargo.toml
     //:vendor/opentelemetry-proto/Cargo.toml
     //:vendor/opentelemetry-semantic-conventions/Cargo.toml
     //:vendor/opentelemetry_sdk/Cargo.toml
     //:vendor/outref/Cargo.toml
     //:vendor/overload/Cargo.toml
     //:vendor/p256/Cargo.toml
     //:vendor/parking/Cargo.toml
     //:vendor/parking_lot/Cargo.toml
     //:vendor/parking_lot_core/Cargo.toml
     //:vendor/parse-display/Cargo.toml
     //:vendor/parse-display-derive/Cargo.toml
     //:vendor/paste/Cargo.toml
     //:vendor/pbkdf2/Cargo.toml
     //:vendor/percent-encoding/Cargo.toml
     //:vendor/petgraph/Cargo.toml
     //:vendor/pin-project/Cargo.toml
     //:vendor/pin-project-internal/Cargo.toml
     //:vendor/pin-project-lite/Cargo.toml
     //:vendor/pin-utils/Cargo.toml
     //:vendor/pkcs8/Cargo.toml
     //:vendor/pkg-config/Cargo.toml
     //:vendor/plotters/Cargo.toml
     //:vendor/plotters-backend/Cargo.toml
     //:vendor/plotters-svg/Cargo.toml
     //:vendor/polling/Cargo.toml
     //:vendor/portable-atomic/Cargo.toml
     //:vendor/portable-atomic-util/Cargo.toml
     //:vendor/powerfmt/Cargo.toml
     //:vendor/ppv-lite86/Cargo.toml
     //:vendor/prettyplease/Cargo.toml
     //:vendor/proc-macro-error/Cargo.toml
     //:vendor/proc-macro-error-attr/Cargo.toml
     //:vendor/proc-macro2/Cargo.toml
     //:vendor/prost/Cargo.toml
     //:vendor/prost-build/Cargo.toml
     //:vendor/prost-derive/Cargo.toml
     //:vendor/prost-types/Cargo.toml
     //:vendor/quanta/Cargo.toml
     //:vendor/quick-xml/Cargo.toml
     //:vendor/quick-xml-0.31.0/Cargo.toml
     //:vendor/quinn/Cargo.toml
     //:vendor/quinn-proto/Cargo.toml
     //:vendor/quinn-udp/Cargo.toml
     //:vendor/quote/Cargo.toml
     //:vendor/rand/Cargo.toml
     //:vendor/rand-0.7.3/Cargo.toml
     //:vendor/rand_chacha/Cargo.toml
     //:vendor/rand_chacha-0.2.2/Cargo.toml
     //:vendor/rand_core/Cargo.toml
     //:vendor/rand_core-0.5.1/Cargo.toml
     //:vendor/rand_distr/Cargo.toml
     //:vendor/rand_hc/Cargo.toml
     //:vendor/raw-cpuid/Cargo.toml
     //:vendor/rayon/Cargo.toml
     //:vendor/rayon-core/Cargo.toml
     //:vendor/redox_syscall/Cargo.toml
     //:vendor/redox_syscall-0.3.5/Cargo.toml
     //:vendor/regex/Cargo.toml
     //:vendor/regex-automata/Cargo.toml
     //:vendor/regex-automata-0.1.10/Cargo.toml
     //:vendor/regex-lite/Cargo.toml
     //:vendor/regex-syntax/Cargo.toml
     //:vendor/regex-syntax-0.6.29/Cargo.toml
     //:vendor/reqwest/Cargo.toml
     //:vendor/rfc6979/Cargo.toml
     //:vendor/ring/Cargo.toml
     //:vendor/rustc-demangle/Cargo.toml
     //:vendor/rustc-hash/Cargo.toml
     //:vendor/rustc-hash-1.1.0/Cargo.toml
     //:vendor/rustc_version/Cargo.toml
     //:vendor/rustix/Cargo.toml
     //:vendor/rustls/Cargo.toml
     //:vendor/rustls-0.21.12/Cargo.toml
     //:vendor/rustls-native-certs/Cargo.toml
     //:vendor/rustls-native-certs-0.6.3/Cargo.toml
     //:vendor/rustls-native-certs-0.7.3/Cargo.toml
     //:vendor/rustls-pemfile/Cargo.toml
     //:vendor/rustls-pemfile-1.0.4/Cargo.toml
     //:vendor/rustls-pki-types/Cargo.toml
     //:vendor/rustls-webpki/Cargo.toml
     //:vendor/rustls-webpki-0.101.7/Cargo.toml
     //:vendor/rustversion/Cargo.toml
     //:vendor/ryu/Cargo.toml
     //:vendor/same-file/Cargo.toml
     //:vendor/schannel/Cargo.toml
     //:vendor/scoped-tls/Cargo.toml
     //:vendor/scopeguard/Cargo.toml
     //:vendor/scram-rs/Cargo.toml
     //:vendor/sct/Cargo.toml
     //:vendor/seahash/Cargo.toml
     //:vendor/sec1/Cargo.toml
     //:vendor/security-framework/Cargo.toml
     //:vendor/security-framework-2.11.1/Cargo.toml
     //:vendor/security-framework-sys/Cargo.toml
     //:vendor/semver/Cargo.toml
     //:vendor/serde/Cargo.toml
     //:vendor/serde_derive/Cargo.toml
     //:vendor/serde_fmt/Cargo.toml
     //:vendor/serde_json/Cargo.toml
     //:vendor/serde_path_to_error/Cargo.toml
     //:vendor/serde_qs/Cargo.toml
     //:vendor/serde_repr/Cargo.toml
     //:vendor/serde_urlencoded/Cargo.toml
     //:vendor/serde_with/Cargo.toml
     //:vendor/serde_with_macros/Cargo.toml
     //:vendor/sha-1/Cargo.toml
     //:vendor/sha1/Cargo.toml
     //:vendor/sha2/Cargo.toml
     //:vendor/sharded-slab/Cargo.toml
     //:vendor/shlex/Cargo.toml
     //:vendor/signal-hook-registry/Cargo.toml
     //:vendor/signature/Cargo.toml
     //:vendor/sketches-ddsketch/Cargo.toml
     //:vendor/slab/Cargo.toml
     //:vendor/smallvec/Cargo.toml
     //:vendor/snafu/Cargo.toml
     //:vendor/snafu-derive/Cargo.toml
     //:vendor/snap/Cargo.toml
     //:vendor/socket2/Cargo.toml
     //:vendor/spin/Cargo.toml
     //:vendor/spki/Cargo.toml
     //:vendor/stable_deref_trait/Cargo.toml
     //:vendor/stateright/Cargo.toml
     //:vendor/stretto/Cargo.toml
     //:vendor/strsim/Cargo.toml
     //:vendor/structmeta/Cargo.toml
     //:vendor/structmeta-derive/Cargo.toml
     //:vendor/structured-logger/Cargo.toml
     //:vendor/subtle/Cargo.toml
     //:vendor/sval/Cargo.toml
     //:vendor/sval_buffer/Cargo.toml
     //:vendor/sval_dynamic/Cargo.toml
     //:vendor/sval_fmt/Cargo.toml
     //:vendor/sval_json/Cargo.toml
     //:vendor/sval_nested/Cargo.toml
     //:vendor/sval_ref/Cargo.toml
     //:vendor/sval_serde/Cargo.toml
     //:vendor/syn/Cargo.toml
     //:vendor/syn-1.0.109/Cargo.toml
     //:vendor/sync_wrapper/Cargo.toml
     //:vendor/synstructure/Cargo.toml
     //:vendor/tempfile/Cargo.toml
     //:vendor/testcontainers/Cargo.toml
     //:vendor/thiserror/Cargo.toml
     //:vendor/thiserror-1.0.69/Cargo.toml
     //:vendor/thiserror-impl/Cargo.toml
     //:vendor/thiserror-impl-1.0.69/Cargo.toml
     //:vendor/thread_local/Cargo.toml
     //:vendor/time/Cargo.toml
     //:vendor/time-core/Cargo.toml
     //:vendor/time-macros/Cargo.toml
     //:vendor/tiny_http/Cargo.toml
     //:vendor/tinystr/Cargo.toml
     //:vendor/tinytemplate/Cargo.toml
     //:vendor/tinyvec/Cargo.toml
     //:vendor/tinyvec_macros/Cargo.toml
     //:vendor/tokio/Cargo.toml
     //:vendor/tokio-macros/Cargo.toml
     //:vendor/tokio-native-tls/Cargo.toml
     //:vendor/tokio-retry/Cargo.toml
     //:vendor/tokio-rustls/Cargo.toml
     //:vendor/tokio-rustls-0.24.1/Cargo.toml
     //:vendor/tokio-stream/Cargo.toml
     //:vendor/tokio-tar/Cargo.toml
     //:vendor/tokio-test/Cargo.toml
     //:vendor/tokio-util/Cargo.toml
     //:vendor/tonic/Cargo.toml
     //:vendor/tonic-build/Cargo.toml
     //:vendor/tower/Cargo.toml
     //:vendor/tower-0.4.13/Cargo.toml
     //:vendor/tower-layer/Cargo.toml
     //:vendor/tower-service/Cargo.toml
     //:vendor/tracing/Cargo.toml
     //:vendor/tracing-attributes/Cargo.toml
     //:vendor/tracing-core/Cargo.toml
     //:vendor/tracing-log/Cargo.toml
     //:vendor/tracing-opentelemetry/Cargo.toml
     //:vendor/tracing-serde/Cargo.toml
     //:vendor/tracing-subscriber/Cargo.toml
     //:vendor/triomphe/Cargo.toml
     //:vendor/try-lock/Cargo.toml
     //:vendor/turmoil/Cargo.toml
     //:vendor/typeid/Cargo.toml
     //:vendor/typenum/Cargo.toml
     //:vendor/unicode-ident/Cargo.toml
     //:vendor/unicode-segmentation/Cargo.toml
     //:vendor/untrusted/Cargo.toml
     //:vendor/url/Cargo.toml
     //:vendor/urlencoding/Cargo.toml
     //:vendor/utf16_iter/Cargo.toml
     //:vendor/utf8_iter/Cargo.toml
     //:vendor/utf8parse/Cargo.toml
     //:vendor/uuid/Cargo.toml
     //:vendor/valuable/Cargo.toml
     //:vendor/value-bag/Cargo.toml
     //:vendor/value-bag-serde1/Cargo.toml
     //:vendor/value-bag-sval2/Cargo.toml
     //:vendor/vcpkg/Cargo.toml
     //:vendor/version_check/Cargo.toml
     //:vendor/vsimd/Cargo.toml
     //:vendor/waker-fn/Cargo.toml
     //:vendor/walkdir/Cargo.toml
     //:vendor/want/Cargo.toml
     //:vendor/wasi/Cargo.toml
     //:vendor/wasi-0.9.0+wasi-snapshot-preview1/Cargo.toml
     //:vendor/wasm-bindgen/Cargo.toml
     //:vendor/wasm-bindgen-backend/Cargo.toml
     //:vendor/wasm-bindgen-futures/Cargo.toml
     //:vendor/wasm-bindgen-macro/Cargo.toml
     //:vendor/wasm-bindgen-macro-support/Cargo.toml
     //:vendor/wasm-bindgen-shared/Cargo.toml
     //:vendor/wasm-streams/Cargo.toml
     //:vendor/web-sys/Cargo.toml
     //:vendor/web-time/Cargo.toml
     //:vendor/wg/Cargo.toml
     //:vendor/which/Cargo.toml
     //:vendor/winapi/Cargo.toml
     //:vendor/winapi-i686-pc-windows-gnu/Cargo.toml
     //:vendor/winapi-util/Cargo.toml
     //:vendor/winapi-x86_64-pc-windows-gnu/Cargo.toml
     //:vendor/windows-core/Cargo.toml
     //:vendor/windows-registry/Cargo.toml
     //:vendor/windows-result/Cargo.toml
     //:vendor/windows-strings/Cargo.toml
     //:vendor/windows-sys/Cargo.toml
     //:vendor/windows-sys-0.48.0/Cargo.toml
     //:vendor/windows-sys-0.52.0/Cargo.toml
     //:vendor/windows-targets/Cargo.toml
     //:vendor/windows-targets-0.48.5/Cargo.toml
     //:vendor/windows_aarch64_gnullvm/Cargo.toml
     //:vendor/windows_aarch64_gnullvm-0.48.5/Cargo.toml
     //:vendor/windows_aarch64_msvc/Cargo.toml
     //:vendor/windows_aarch64_msvc-0.48.5/Cargo.toml
     //:vendor/windows_i686_gnu/Cargo.toml
     //:vendor/windows_i686_gnu-0.48.5/Cargo.toml
     //:vendor/windows_i686_gnullvm/Cargo.toml
     //:vendor/windows_i686_msvc/Cargo.toml
     //:vendor/windows_i686_msvc-0.48.5/Cargo.toml
     //:vendor/windows_x86_64_gnu/Cargo.toml
     //:vendor/windows_x86_64_gnu-0.48.5/Cargo.toml
     //:vendor/windows_x86_64_gnullvm/Cargo.toml
     //:vendor/windows_x86_64_gnullvm-0.48.5/Cargo.toml
     //:vendor/windows_x86_64_msvc/Cargo.toml
     //:vendor/windows_x86_64_msvc-0.48.5/Cargo.toml
     //:vendor/write16/Cargo.toml
     //:vendor/writeable/Cargo.toml
     //:vendor/xattr/Cargo.toml
     //:vendor/xmlparser/Cargo.toml
     //:vendor/xxhash-rust/Cargo.toml
     //:vendor/yoke/Cargo.toml
     //:vendor/yoke-derive/Cargo.toml
     //:vendor/zerocopy/Cargo.toml
     //:vendor/zerocopy-derive/Cargo.toml
     //:vendor/zerofrom/Cargo.toml
     //:vendor/zerofrom-derive/Cargo.toml
     //:vendor/zeroize/Cargo.toml
     //:vendor/zerovec/Cargo.toml
     //:vendor/zerovec-derive/Cargo.toml
     //:vendor/zstd/Cargo.toml
     //:vendor/zstd-safe/Cargo.toml
     //:vendor/zstd-sys/Cargo.toml.
ERROR: error evaluating module extension crate in @@rules_rust+//crate_universe:extension.bzl
INFO: Elapsed time: 0.142s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

**Comment by pdeva** [comment]
seems this fixed the issue `common --noincompatible_disallow_empty_glob`

**Comment by UebelAndre** [comment]
> seems this fixed the issue `common --noincompatible_disallow_empty_glob`

I didn’t think that affected repository rules so that being the fix seems surprising but glad you’re unblocked!
