### ISSUE TITLE
`crate_universe` is incompatible with Bazel 8.0.0

### ISSUE THREAD

**Issue by jthemphill** [bazelbuild/rules_rust#3150]
Attempting to build [example `05-deps-cargo`](https://github.com/bazelbuild/examples/blob/b51e3bdd468ce8c4a516d7dca993909dcc84af32/rust-examples/05-deps-cargo/MODULE.bazel#L7) on an M1 Mac. The example builds great on Bazel 7 but fails on Bazel 8.

I made two changes.

First, I bumped [`.bazelversion` in the examples repository](https://github.com/bazelbuild/examples/blob/b51e3bdd468ce8c4a516d7dca993909dcc84af32/rust-examples/.bazelversion#L1):

```diff
- 7.2.1
+ 8.0.0
```

The build then failed. I thought maybe the newest version of `rules_rust` could address the issue. So I bumped [the version of `rules_rust` in `MODULE.bazel`](https://github.com/bazelbuild/examples/blob/b51e3bdd468ce8c4a516d7dca993909dcc84af32/rust-examples/05-deps-cargo/MODULE.bazel#L7):

```diff
- bazel_dep(name = "rules_rust", version = "0.47.1")
+ bazel_dep(name = "rules_rust", version = "0.56.0")
```

Running the build with Bazel 8 and `rules_rust` 0.56.0:

```sh
05-deps-cargo % bazel build //...
WARNING: Couldn't auto load rules or symbols, because no dependency on module/repository 'rules_android' found. This will result in a failure if there's a reference to those rules or symbols.
ERROR: /private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/external/rules_rust+/crate_universe/extensions.bzl:363:17: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/external/rules_rust+/crate_universe/extensions.bzl", line 459, column 37, in _crate_impl
                _generate_hub_and_spokes(
        File "/private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/external/rules_rust+/crate_universe/extensions.bzl", line 144, column 16, in _generate_hub_and_spokes
                cargo_bazel([
        File "/private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/external/rules_rust+/crate_universe/extensions.bzl", line 363, column 17, in run
                fail("%s returned with exit code %d:\n%s" % (pretty_args, result.return_code, result.stderr))
Error in fail: /private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/modextwd/rules_rust++crate/cargo-bazel generate --cargo-lockfile /Users/jhemphill/oss/bazelbuild/examples/rust-examples/05-deps-cargo/Cargo.lock --config /private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/modextwd/rules_rust++crate/crates/config.json --splicing-manifest /private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/modextwd/rules_rust++crate/crates/splicing_manifest.json --repository-dir /private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/modextwd/rules_rust++crate/crates --metadata /private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/modextwd/rules_rust++crate/crates/splicing-output/metadata.json --repin --lockfile /private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/modextwd/rules_rust++crate/crates/lockfile.json --nonhermetic-root-bazel-workspace-dir /Users/jhemphill/oss/bazelbuild/examples/rust-examples/05-deps-cargo --paths-to-track /private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/modextwd/rules_rust++crate/paths-to-track --warnings-output-path /private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/modextwd/rules_rust++crate/warnings-output-file --cargo /private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/external/rules_rust++rust_host_tools+rust_host_tools/bin/cargo --rustc /private/var/tmp/_bazel_jhemphill/a3385e184eb75f0cb537a24f915a0ff0/external/rules_rust++rust_host_tools+rust_host_tools/bin/rustc returned with exit code 1:
Error: Package "all_crate_deps" target "all_crate_deps" had an absolute source path "/dev/null", which is not supported
```

**Comment by ssmall** [comment]
I'm experiencing the same issue, have had to stick with rules_rust 0.47.1 because of it. Can confirm the issue is still present with 0.57.1.

**Comment by UebelAndre** [comment]
This has been a long running effort to address. I created https://github.com/bazelbuild/rules_rust/pull/3077 as the change which would demonstrate support for Bazel 8 but it's been an absolutely monstrous endeavor to get through. There aren't many jobs that are failing but the remaining are certainly confusing. Any support from the community would be greatly appreciated!

**Comment by ssmall** [comment]
Can we re-open the issue? I am still seeing this in 0.59.1, which IIUC should contain the fix.

**Comment by UebelAndre** [comment]
I think we have plenty of evidence that rules_rust works with Bazel 8.x so whatever is going on is likely a more specific issue. Can we instead open a new one?
