### ISSUE TITLE
Error `(rule 'rust_library') doesn't contain declared provider 'CcInfo'` for cargo raze deps

### ISSUE THREAD

**Issue by TimothyKlim** [bazelbuild/rules_rust#368]
Hello!
I have an issue in my rust library as JNI after upgrading rules_rust to this commit #361:
```
load("@//:config.bzl", "rustc_flags")
load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "somelib",
    srcs = ["src/lib.rs"],
    crate_root = "src/lib.rs",
    crate_type = "cdylib",
    rustc_flags = rustc_flags,
    deps = [
        "//cargo:jni",
    ],
    visibility = ["//visibility:public"],
)
```

bazel build:
```
Traceback (most recent call last):
        File "/home/xxx/Projects/testapp/BUILD.bazel", line 4
                rust_binary(name = 'joiner.so')
        File "/home/xxx/.cache/bazel/_bazel_johndoe/96364899299eda1f2874771f867b1be1/external/io_bazel_rules_rust/rust/private/rust.bzl", line 169, in _rust_binary_impl
                rustc_compile_action(ctx = ctx, <2 more arguments>)
        File "/home/xxx/.cache/bazel/_bazel_johndoe/96364899299eda1f2874771f867b1be1/external/io_bazel_rules_rust/rust/private/rustc.bzl", line 508, in rustc_compile_action
                establish_cc_info(ctx, <4 more arguments>)
        File "/home/xxx/.cache/bazel/_bazel_johndoe/96364899299eda1f2874771f867b1be1/external/io_bazel_rules_rust/rust/private/rustc.bzl", line 551, in establish_cc_info
                dep[CcInfo]
<target //cargo/vendor/jni-0.17.0:jni> (rule 'rust_library') doesn't contain declared provider 'CcInfo'
```

Dependencies has been generated by cargo-raze v0.3.6.

**Comment by damienmg** [comment]
Yes there is an obvious bug I wonder why it was not caught earlier.

**Comment by damienmg** [comment]
Ok it wasn't caught because it would be triggered only with staticlib / cdylib

**Comment by TimothyKlim** [comment]
Now it's working again. Thank you!
