### ISSUE TITLE
Build broken on FreeBSD

### ISSUE THREAD

**Issue by yesudeep** [bazelbuild/rules_rust#396]
```shell
...
WARNING: Download from https://static.rust-lang.org/dist/rustfmt-1.4.8-x86_64-unknown-freebsd.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'rust_freebsd_x86_64':
   Traceback (most recent call last):
	File "/usr/home/yesudeep/.cache/bazel/_bazel_yesudeep/21298c98f6c16e14c7170c698f3518aa/external/io_bazel_rules_rust/rust/repositories.bzl", line 486
		_load_rustfmt(ctx)
	File "/usr/home/yesudeep/.cache/bazel/_bazel_yesudeep/21298c98f6c16e14c7170c698f3518aa/external/io_bazel_rules_rust/rust/repositories.bzl", line 367, in _load_rustfmt
		load_arbitrary_tool(ctx, <5 more arguments>)
	File "/usr/home/yesudeep/.cache/bazel/_bazel_yesudeep/21298c98f6c16e14c7170c698f3518aa/external/io_bazel_rules_rust/rust/repositories.bzl", line 347, in load_arbitrary_tool
		ctx.download(url, <2 more arguments>)
java.io.IOException: Error downloading [https://static.rust-lang.org/dist/rustfmt-1.4.8-x86_64-unknown-freebsd.tar.gz] to /usr/home/yesudeep/.cache/bazel/_bazel_yesudeep/21298c98f6c16e14c7170c698f3518aa/external/rust_freebsd_x86_64/rustfmt-1.4.8-x86_64-unknown-freebsd.tar.gz: GET returned 404 Not Found
ERROR: /usr/home/yesudeep/.cache/bazel/_bazel_yesudeep/21298c98f6c16e14c7170c698f3518aa/external/raze__rand__0_7_3/BUILD.bazel:32:13: @raze__rand__0_7_3//:rand depends on @rust_freebsd_x86_64//:toolchain_for_x86_64-unknown-freebsd_impl in repository @rust_freebsd_x86_64 which failed to fetch. no such package '@rust_freebsd_x86_64//': Traceback (most recent call last):
	File "/usr/home/yesudeep/.cache/bazel/_bazel_yesudeep/21298c98f6c16e14c7170c698f3518aa/external/io_bazel_rules_rust/rust/repositories.bzl", line 486
		_load_rustfmt(ctx)
	File "/usr/home/yesudeep/.cache/bazel/_bazel_yesudeep/21298c98f6c16e14c7170c698f3518aa/external/io_bazel_rules_rust/rust/repositories.bzl", line 367, in _load_rustfmt
		load_arbitrary_tool(ctx, <5 more arguments>)
	File "/usr/home/yesudeep/.cache/bazel/_bazel_yesudeep/21298c98f6c16e14c7170c698f3518aa/external/io_bazel_rules_rust/rust/repositories.bzl", line 347, in load_arbitrary_tool
		ctx.download(url, <2 more arguments>)
java.io.IOException: Error downloading [https://static.rust-lang.org/dist/rustfmt-1.4.8-x86_64-unknown-freebsd.tar.gz] to /usr/home/yesudeep/.cache/bazel/_bazel_yesudeep/21298c98f6c16e14c7170c698f3518aa/external/rust_freebsd_x86_64/rustfmt-1.4.8-x86_64-unknown-freebsd.tar.gz: GET returned 404 Not Found
ERROR: Analysis of target '//third_party/cargo:rand' failed; build aborted: Analysis failed
INFO: Elapsed time: 6.242s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (18 packages loaded, 238 targets configured
```

**Comment by yesudeep** [comment]
Fixed by https://github.com/bazelbuild/rules_rust/pull/397
