### ISSUE TITLE
Outstanding Migration flags

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#406]
Just making this issue to make it easier to track the work to fix these

```
Migration is needed for the following flags:
  --//tools/build_defs/pkg:incompatible_no_build_defs_pkg (Bazel 4.0: https://github.com/bazelbuild/bazel/issues/8857)
  --incompatible_load_cc_rules_from_bzl (Bazel 4.0: https://github.com/bazelbuild/bazel/issues/8743)
  --incompatible_proto_output_v2 (Bazel 4.0: https://github.com/bazelbuild/bazel/issues/10358)
  --incompatible_require_linker_input_cc_api (Bazel 4.0: https://github.com/bazelbuild/bazel/issues/10860)
  --incompatible_restrict_string_escapes (Bazel 4.0: https://github.com/bazelbuild/bazel/issues/8380)
  --incompatible_use_platforms_repo_for_constraints (Bazel 4.0: https://github.com/bazelbuild/bazel/issues/8622)
```

**Comment by UebelAndre** [comment]
@damienmg is it possible to get a new run of https://buildkite.com/bazel/rules-rust-plus-bazelisk-migrate ?

**Comment by damienmg** [comment]
Done https://buildkite.com/bazel/rules-rust-plus-bazelisk-migrate/builds/4.

**Comment by UebelAndre** [comment]
@damienmg  I think this just failed to build in general. I see the following errors but not any output about migration flags.
```output
2020/11/10 09:52:34 Downloading https://releases.bazel.build/3.7.0/release/bazel-3.7.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Traceback (most recent call last):
  File "aggregate_incompatible_flags_test_result.py", line 606, in <module>
    sys.exit(main())
  File "aggregate_incompatible_flags_test_result.py", line 586, in main
    already_failing_jobs, failed_jobs_per_flag, details_per_flag
  File "aggregate_incompatible_flags_test_result.py", line 414, in print_result_info
    print_flags_need_to_migrate(failed_jobs_per_flag, details_per_flag)
  File "aggregate_incompatible_flags_test_result.py", line 292, in print_flags_need_to_migrate
    bazel_mark = ":bazel:" if bazelci.DOWNSTREAM_PROJECTS[pipeline].get("owned_by_bazel") else ""
KeyError: ''
```

**Comment by damienmg** [comment]
Then I cannot run the project, it needs to be run as part of a Bazel downstream pipeline.

**Comment by UebelAndre** [comment]
Do you know who might have the power to run it?

**Comment by UebelAndre** [comment]
I actually think most of these are taken care of at this point. There only appears to be one new one:
`incompatible_use_platforms_repo_for_constraints`

```
Migration is needed for the following flags:
  --//tools/build_defs/pkg:incompatible_no_build_defs_pkg (Bazel TBD: https://github.com/bazelbuild/bazel/issues/8857)
  --incompatible_proto_output_v2 (Bazel 4.0: https://github.com/bazelbuild/bazel/issues/10358)
  --incompatible_use_platforms_repo_for_constraints (Bazel 5.0: https://github.com/bazelbuild/bazel/issues/8622)
```

`incompatible_proto_output_v2` is an `aquery` command and is expected to fail a `build` command (https://github.com/bazelbuild/bazelisk/issues/147). I think these rules are in alignment with Bazel 4.0.

**Comment by UebelAndre** [comment]
I think this is basically done. Closing
