### ISSUE TITLE
Clean up bazel_version usage

### ISSUE THREAD

**Issue by dfreese** [bazelbuild/rules_rust#462]
The usage of bazel version predates bazel 1.0, so check to see if it is still necessary.    As brought up in #460, native.bazel_version may provide enough of a replacement.

The repository rule in workspace.bzl was causing conflicts with other bazel repositories that pull in a @bazel_version

**Comment by wchargin** [comment]
Just getting back to this. Attempting to replace `BAZEL_VERSION` with
`native.bazel_version` does still fail:

<details>
<summary>Diff and shell session with “Error: no native function or rule 'bazel_version'”</summary>

```
wchargin@wchargin-xenial-42:~/rules_rust/examples$ bazel info release
release 3.7.0
wchargin@wchargin-xenial-42:~/rules_rust/examples$ git diff
diff --git a/rust/private/rustc.bzl b/rust/private/rustc.bzl
index 9968f84..2fd54fc 100644
--- a/rust/private/rustc.bzl
+++ b/rust/private/rustc.bzl
@@ -230,12 +230,13 @@ def get_cc_toolchain(ctx):
         tuple: A tuple of (CcToolchain, FeatureConfiguration)
     """
     cc_toolchain = find_cpp_toolchain(ctx)
+    bzv = native.bazel_version()
 
     kwargs = {
         "ctx": ctx,
-    } if len(BAZEL_VERSION) == 0 or versions.is_at_least(
+    } if len(bzv) == 0 or versions.is_at_least(
         "0.25.0",
-        BAZEL_VERSION,
+        bzv,
     ) else {}
     feature_configuration = cc_common.configure_features(
         cc_toolchain = cc_toolchain,
wchargin@wchargin-xenial-42:~/rules_rust/examples$ bazel run //hello_world
ERROR: /home/wchargin/rules_rust/examples/hello_lib/BUILD:11:13: in rust_library rule //hello_lib:hello_lib: 
Traceback (most recent call last):
        File "/home/wchargin/.cache/bazel/_bazel_wchargin/43870155d296519f534e54a7f60aabf1/external/io_bazel_rules_rust/rust/private/rust.bzl", line 163, column 32, in _rust_library_impl
                return rustc_compile_action(
        File "/home/wchargin/.cache/bazel/_bazel_wchargin/43870155d296519f534e54a7f60aabf1/external/io_bazel_rules_rust/rust/private/rustc.bzl", line 600, column 59, in rustc_compile_action
                cc_toolchain, feature_configuration = get_cc_toolchain(ctx)
        File "/home/wchargin/.cache/bazel/_bazel_wchargin/43870155d296519f534e54a7f60aabf1/external/io_bazel_rules_rust/rust/private/rustc.bzl", line 233, column 17, in get_cc_toolchain
                bzv = native.bazel_version()
Error: no native function or rule 'bazel_version'
Available attributes: aar_import, action_listener, alias, android_binary, android_device, android_device_script_fixture, android_host_service_fixture, android_instrumentation_test, android_library, android_local_test, android_sdk, android_tools_defaults_jar, apple_binary, apple_cc_toolchain, apple_static_library, available_xcodes, cc_binary, cc_host_toolchain_alias, cc_import, cc_libc_top_alias, cc_library, cc_proto_library, cc_test, cc_toolchain, cc_toolchain_alias, cc_toolchain_suite, config_feature_flag, config_setting, constraint_setting, constraint_value, environment, existing_rule, existing_rules, exports_files, extra_action, fdo_prefetch_hints, fdo_profile, filegroup, genquery, genrule, glob, j2objc_library, java_binary, java_import, java_library, java_lite_proto_library, java_package_configuration, java_plugin, java_proto_library, java_runtime, java_runtime_alias, java_test, java_toolchain, java_toolchain_alias, label_flag, label_setting, ninja_build, ninja_graph, objc_import, objc_library, package, package_group, package_name, platform, propeller_optimize, proto_lang_toolchain, proto_library, py_binary, py_library, py_runtime, py_test, repository_name, sh_binary, sh_library, sh_test, test_suite, toolchain, toolchain_type, xcode_config, xcode_config_alias, xcode_version
ERROR: Analysis of target '//hello_world:hello_world' failed; build aborted: Analysis of target '//hello_lib:hello_lib' failed
INFO: Elapsed time: 0.140s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

</details>

This is consistent with the (still open) upstream issue’s description of
it not working in macros or rules:
<https://github.com/bazelbuild/bazel/issues/8305>

From the [discussion on that issue][cm], it sounds like the Bazel devs
aren’t interested in making this easier:

> I don't really want to encourage code that behaves differently based on the version number. You can use versions.bzl to tell users when they have an old version of Bazel.
> 
> Do you really have to support old versions of Bazel with a different code path?

So it sounds like their preferred solution would be that we drop
compatibility with Bazel versions old enough to require special
codepaths. That looks like it would entail bumping our minimum
supported version from 0.17.1 to 0.25.0, released 2019-05-01. Up to you
whether/when to make that cut.

[cm]: https://github.com/bazelbuild/bazel/issues/8305#issuecomment-494833906
